// swift-tools-version:6.0
//
// entity-core-protocol-swift — peer #7 of the Entity Core arch.
// Generated by /entity-rosetta from spec-data/v7.74 + profile.toml (S2: codec).
//
// Dependency pins (S11 supply-chain — every dep ≥30 days old at pin time):
//   swift-crypto 3.14.0  (2025-08-06, ~10 mo)  — Curve25519.Signing (Ed25519) + SHA256/384/512
//   swift-asn1   1.7.0   (2026-04-16, ~59 d)   — TRANSITIVE dep of swift-crypto; pinned EXPLICITLY
//                                                because SwiftPM auto-resolves to 1.7.1 (~6 d) which
//                                                violates the S11 30-day cool-down. See A-SW-005.
// Both are locked by exact version in the committed Package.resolved.
import PackageDescription

let package = Package(
    name: "entity-core-protocol-swift",
    products: [
        .library(name: "EntityCoreProtocol", targets: ["EntityCoreProtocol"]),
        .executable(name: "entity-peer-swift", targets: ["Host"]),   // S4-ready host
        .executable(name: "smoke", targets: ["Smoke"]),              // S3 smoke runner
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-crypto.git", exact: "3.14.0"),
        // Explicit transitive pin (A-SW-005): hold swift-asn1 at 1.7.0 to satisfy the
        // S11 ≥30-day floor; do NOT let SwiftPM float it to 1.7.1.
        .package(url: "https://github.com/apple/swift-asn1.git", exact: "1.7.0"),
    ],
    targets: [
        .target(
            name: "EntityCoreProtocol",
            dependencies: [
                .product(name: "Crypto", package: "swift-crypto"),
            ]
        ),
        .executableTarget(
            name: "Host",
            dependencies: ["EntityCoreProtocol"]
        ),
        .executableTarget(
            name: "Smoke",
            dependencies: ["EntityCoreProtocol"]
        ),
        .testTarget(
            name: "EntityCoreProtocolTests",
            dependencies: ["EntityCoreProtocol"],
            // The normative ECF conformance corpus lives outside the package tree
            // (shared across all peers); it is loaded by absolute path at test time,
            // so no bundled resource here.
            resources: []
        ),
    ]
)
