--  entity_core-protocol-type_registry.ads — the §9.5 core-type floor (53 types).
--
--  GENERATED by tools/gen_type_registry.py from the STAMPED v7.75 cohort oracle
--  entity-core-go @ 62044c5 (types.RegisterCoreTypes + the validate-peer
--  runTypeSystem registry setup). Each floor type is served at
--  system/type/<name> as a `system/type` entity whose data is the canonical
--  ECF-encoded TypeDefinition payload — byte-identical to the oracle, so the
--  validate-peer type_system _match (content_hash equality) passes 53/53.
--  DO NOT EDIT BY HAND. Regenerate when the oracle moves (oracle-rebuild rule).

with Entity_Core.Protocol.Store;

package Entity_Core.Protocol.Type_Registry is

   --  Publish the 53 core-floor type definitions into Store under the local
   --  peer's namespace ("/" & Local & "/system/type/<name>").
   procedure Publish
     (St    : Entity_Core.Protocol.Store.Store_Access;
      Local : String);

   --  Count of floor types (for self-test).
   Floor_Count : constant := 53;

end Entity_Core.Protocol.Type_Registry;
