(* GENERATED from test-vectors type-registry-shapes.json (the cross-impl Go-rendered
   type model) — the in-code core-type override table (render-from-model design).
   53 core types per V7 §9.5. Regenerate with tools/gen-typedefs.py on a V7 bump;
   diffed byte-for-byte against type-registry-vectors-v1 in test/type_registry.ml. *)

let core_types : (string * Cbor.t) list = [
  ("primitive/any", Cbor.Map [(Cbor.Text "name", Cbor.Text "primitive/any")]);
  ("primitive/bool", Cbor.Map [(Cbor.Text "name", Cbor.Text "primitive/bool")]);
  ("primitive/bytes", Cbor.Map [(Cbor.Text "name", Cbor.Text "primitive/bytes")]);
  ("primitive/float", Cbor.Map [(Cbor.Text "name", Cbor.Text "primitive/float")]);
  ("primitive/int", Cbor.Map [(Cbor.Text "name", Cbor.Text "primitive/int")]);
  ("primitive/null", Cbor.Map [(Cbor.Text "name", Cbor.Text "primitive/null")]);
  ("primitive/string", Cbor.Map [(Cbor.Text "name", Cbor.Text "primitive/string")]);
  ("primitive/uint", Cbor.Map [(Cbor.Text "name", Cbor.Text "primitive/uint")]);
  ("entity", Cbor.Map [(Cbor.Text "name", Cbor.Text "entity"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "data", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/any")]); (Cbor.Text "type", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string")])])]);
  ("core/entity", Cbor.Map [(Cbor.Text "name", Cbor.Text "core/entity"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "content_hash", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/hash")]); (Cbor.Text "data", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/any")]); (Cbor.Text "type", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string")])])]);
  ("core/envelope", Cbor.Map [(Cbor.Text "name", Cbor.Text "core/envelope"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "included", Cbor.Map [(Cbor.Text "optional", Cbor.Bool true); (Cbor.Text "map_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "core/entity")]); (Cbor.Text "key_type", Cbor.Text "system/hash")]); (Cbor.Text "root", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "core/entity")])])]);
  ("system/envelope", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/envelope"); (Cbor.Text "extends", Cbor.Text "core/envelope")]);
  ("system/protocol/envelope", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/protocol/envelope"); (Cbor.Text "extends", Cbor.Text "core/envelope")]);
  ("system/hash", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/hash"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "digest", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/bytes")]); (Cbor.Text "format_code", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/uint"); (Cbor.Text "byte_size", Cbor.Uint 1L)])]); (Cbor.Text "extends", Cbor.Text "primitive/bytes"); (Cbor.Text "layout", Cbor.Array [Cbor.Text "format_code"; Cbor.Text "digest"])]);
  ("system/peer", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/peer"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "key_type", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string")]); (Cbor.Text "peer_id", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/peer-id")]); (Cbor.Text "public_key", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/bytes")])])]);
  ("system/peer-id", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/peer-id"); (Cbor.Text "extends", Cbor.Text "primitive/string")]);
  ("system/signature", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/signature"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "algorithm", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string")]); (Cbor.Text "signature", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/bytes")]); (Cbor.Text "signer", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/hash")]); (Cbor.Text "target", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/hash")])])]);
  ("system/protocol/connect/authenticate", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/protocol/connect/authenticate"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "key_type", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string")]); (Cbor.Text "nonce", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/bytes")]); (Cbor.Text "peer_id", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/peer-id")]); (Cbor.Text "public_key", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/bytes")])])]);
  ("system/protocol/connect/hello", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/protocol/connect/hello"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "compression", Cbor.Map [(Cbor.Text "optional", Cbor.Bool true); (Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string")])]); (Cbor.Text "encryption", Cbor.Map [(Cbor.Text "optional", Cbor.Bool true); (Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string")])]); (Cbor.Text "hash_formats", Cbor.Map [(Cbor.Text "optional", Cbor.Bool true); (Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string")])]); (Cbor.Text "key_types", Cbor.Map [(Cbor.Text "optional", Cbor.Bool true); (Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string")])]); (Cbor.Text "nonce", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/bytes")]); (Cbor.Text "peer_id", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/peer-id")]); (Cbor.Text "protocols", Cbor.Map [(Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string")])]); (Cbor.Text "timestamp", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/uint")])])]);
  ("system/protocol/error", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/protocol/error"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "code", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string")]); (Cbor.Text "message", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "rejected_marker", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/hash"); (Cbor.Text "optional", Cbor.Bool true)])])]);
  ("system/protocol/execute", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/protocol/execute"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "author", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/hash"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "bounds", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/bounds"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "capability", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/hash"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "deliver_to", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/delivery-spec"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "deliver_token", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/hash"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "durability_request", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/durability-request"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "operation", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string")]); (Cbor.Text "params", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "core/entity")]); (Cbor.Text "request_id", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string")]); (Cbor.Text "resource", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/protocol/resource-target"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "uri", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/tree/path")])])]);
  ("system/protocol/execute/response", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/protocol/execute/response"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "durability", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/durability-result"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "request_id", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string")]); (Cbor.Text "result", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "core/entity")]); (Cbor.Text "status", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/uint")])])]);
  ("system/protocol/resource-target", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/protocol/resource-target"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "exclude", Cbor.Map [(Cbor.Text "optional", Cbor.Bool true); (Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/tree/path")])]); (Cbor.Text "targets", Cbor.Map [(Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/tree/path")])])])]);
  ("system/capability/grant", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/capability/grant"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "token", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/hash")])])]);
  ("system/capability/grant-entry", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/capability/grant-entry"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "allowances", Cbor.Map [(Cbor.Text "optional", Cbor.Bool true); (Cbor.Text "map_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/any")])]); (Cbor.Text "constraints", Cbor.Map [(Cbor.Text "optional", Cbor.Bool true); (Cbor.Text "map_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/any")])]); (Cbor.Text "handlers", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/capability/path-scope")]); (Cbor.Text "operations", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/capability/id-scope")]); (Cbor.Text "peers", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/capability/id-scope"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "resources", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/capability/path-scope")])])]);
  ("system/capability/id-scope", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/capability/id-scope"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "exclude", Cbor.Map [(Cbor.Text "optional", Cbor.Bool true); (Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string")])]); (Cbor.Text "include", Cbor.Map [(Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string")])])])]);
  ("system/capability/path-scope", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/capability/path-scope"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "exclude", Cbor.Map [(Cbor.Text "optional", Cbor.Bool true); (Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/tree/path")])]); (Cbor.Text "include", Cbor.Map [(Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/tree/path")])])])]);
  ("system/capability/request", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/capability/request"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "grants", Cbor.Map [(Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/capability/grant-entry")])]); (Cbor.Text "ttl_ms", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/uint"); (Cbor.Text "optional", Cbor.Bool true)])])]);
  ("system/capability/revocation", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/capability/revocation"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "reason", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "revoked_at", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/uint")]); (Cbor.Text "token", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/hash")])])]);
  ("system/capability/revoke-request", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/capability/revoke-request"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "reason", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "token", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/hash")])])]);
  ("system/capability/delegate-request", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/capability/delegate-request"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "grants", Cbor.Map [(Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/capability/grant-entry")])]); (Cbor.Text "parent", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/hash")]); (Cbor.Text "ttl_ms", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/uint"); (Cbor.Text "optional", Cbor.Bool true)])])]);
  ("system/capability/delegation-caveats", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/capability/delegation-caveats"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "max_delegation_depth", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/uint"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "max_delegation_ttl", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/uint"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "no_delegation", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/bool"); (Cbor.Text "optional", Cbor.Bool true)])])]);
  ("system/capability/policy-entry", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/capability/policy-entry"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "grants", Cbor.Map [(Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/capability/grant-entry")])]); (Cbor.Text "notes", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "peer_pattern", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string")]); (Cbor.Text "ttl_ms", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/uint"); (Cbor.Text "optional", Cbor.Bool true)])])]);
  ("system/capability/token", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/capability/token"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "created_at", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/uint")]); (Cbor.Text "delegation_caveats", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/capability/delegation-caveats"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "expires_at", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/uint"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "grantee", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/hash")]); (Cbor.Text "granter", Cbor.Map [(Cbor.Text "union_of", Cbor.Array [Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/hash")]; Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/capability/multi-granter")]])]); (Cbor.Text "grants", Cbor.Map [(Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/capability/grant-entry")])]); (Cbor.Text "not_before", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/uint"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "parent", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/hash"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "resource_limits", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/resource-limits"); (Cbor.Text "optional", Cbor.Bool true)])])]);
  ("system/capability/multi-granter", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/capability/multi-granter"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "signers", Cbor.Map [(Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/hash")])]); (Cbor.Text "threshold", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/uint")])])]);
  ("system/handler", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/handler"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "expression_path", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/tree/path"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "interface", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/tree/path")]); (Cbor.Text "internal_scope", Cbor.Map [(Cbor.Text "optional", Cbor.Bool true); (Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/capability/grant-entry")])]); (Cbor.Text "max_scope", Cbor.Map [(Cbor.Text "optional", Cbor.Bool true); (Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/capability/grant-entry")])])])]);
  ("system/handler/interface", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/handler/interface"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "name", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string")]); (Cbor.Text "operations", Cbor.Map [(Cbor.Text "map_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/handler/operation-spec")])]); (Cbor.Text "pattern", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/tree/path")])])]);
  ("system/handler/manifest", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/handler/manifest"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "expression_path", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/tree/path"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "internal_scope", Cbor.Map [(Cbor.Text "optional", Cbor.Bool true); (Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/capability/grant-entry")])]); (Cbor.Text "max_scope", Cbor.Map [(Cbor.Text "optional", Cbor.Bool true); (Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/capability/grant-entry")])]); (Cbor.Text "name", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string")]); (Cbor.Text "operations", Cbor.Map [(Cbor.Text "map_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/handler/operation-spec")])]); (Cbor.Text "pattern", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/tree/path")])]); (Cbor.Text "extends", Cbor.Text "system/handler/interface")]);
  ("system/handler/operation-spec", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/handler/operation-spec"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "input_type", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/type/name"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "output_type", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/type/name"); (Cbor.Text "optional", Cbor.Bool true)])])]);
  ("system/handler/register-request", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/handler/register-request"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "manifest", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/handler/manifest")]); (Cbor.Text "requested_scope", Cbor.Map [(Cbor.Text "optional", Cbor.Bool true); (Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/capability/grant-entry")])]); (Cbor.Text "types", Cbor.Map [(Cbor.Text "optional", Cbor.Bool true); (Cbor.Text "map_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/type")])])])]);
  ("system/handler/register-result", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/handler/register-result"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "grant", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/capability/token")]); (Cbor.Text "pattern", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/tree/path")])])]);
  ("system/tree/get-request", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/tree/get-request"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "limit", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/uint"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "mode", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "offset", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/uint"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "tree_id", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string"); (Cbor.Text "optional", Cbor.Bool true)])])]);
  ("system/tree/put-request", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/tree/put-request"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "entity", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "core/entity"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "expected_hash", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/hash"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "tree_id", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string"); (Cbor.Text "optional", Cbor.Bool true)])])]);
  ("system/tree/listing", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/tree/listing"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "count", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/uint")]); (Cbor.Text "entries", Cbor.Map [(Cbor.Text "map_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/tree/listing-entry")])]); (Cbor.Text "next_page", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/hash"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "offset", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/uint")]); (Cbor.Text "path", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/tree/path")])])]);
  ("system/tree/listing-entry", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/tree/listing-entry"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "has_children", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/bool")]); (Cbor.Text "hash", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/hash"); (Cbor.Text "optional", Cbor.Bool true)])])]);
  ("system/tree/path", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/tree/path"); (Cbor.Text "extends", Cbor.Text "primitive/string")]);
  ("system/type", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/type"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "extends", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/type/name"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "optional", Cbor.Bool true); (Cbor.Text "map_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/type/field-spec")])]); (Cbor.Text "layout", Cbor.Map [(Cbor.Text "optional", Cbor.Bool true); (Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string")])]); (Cbor.Text "name", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/type/name")]); (Cbor.Text "type_args", Cbor.Map [(Cbor.Text "optional", Cbor.Bool true); (Cbor.Text "map_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/type/name")])]); (Cbor.Text "type_params", Cbor.Map [(Cbor.Text "optional", Cbor.Bool true); (Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string")])])])]);
  ("system/type/field-spec", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/type/field-spec"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/type/field-spec"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "byte_size", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/uint"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "constraints", Cbor.Map [(Cbor.Text "optional", Cbor.Bool true); (Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "core/entity")])]); (Cbor.Text "default", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/any"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "key_type", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/type/name"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "map_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/type/field-spec"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "optional", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/bool"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "type_args", Cbor.Map [(Cbor.Text "optional", Cbor.Bool true); (Cbor.Text "map_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/type/name")])]); (Cbor.Text "type_param", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "type_ref", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/type/name"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "union_of", Cbor.Map [(Cbor.Text "optional", Cbor.Bool true); (Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/type/field-spec")])])])]);
  ("system/type/name", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/type/name"); (Cbor.Text "extends", Cbor.Text "primitive/string")]);
  ("system/bounds", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/bounds"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "budget", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/uint"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "cascade_depth", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/uint"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "chain_id", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "parent_chain_id", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "ttl", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/uint"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "visited", Cbor.Map [(Cbor.Text "optional", Cbor.Bool true); (Cbor.Text "array_of", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/tree/path")])])])]);
  ("system/resource-limits", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/resource-limits"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "max_budget", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/uint"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "max_ttl", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/uint"); (Cbor.Text "optional", Cbor.Bool true)]); (Cbor.Text "max_visited_length", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/uint"); (Cbor.Text "optional", Cbor.Bool true)])])]);
  ("system/delivery-spec", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/delivery-spec"); (Cbor.Text "fields", Cbor.Map [(Cbor.Text "operation", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "primitive/string")]); (Cbor.Text "uri", Cbor.Map [(Cbor.Text "type_ref", Cbor.Text "system/tree/path")])])]);
  ("system/deletion-marker", Cbor.Map [(Cbor.Text "name", Cbor.Text "system/deletion-marker")]);
]
