/**
 * entity-core-protocol-typescript — a core protocol peer (V7 Layers 0–4) in
 * TypeScript, generated by the entity-core-keystone `/entity-rosetta` generator.
 *
 * The codec + crypto core is browser-portable (zero `node:*` imports); the peer's
 * transport (`node:net`) is the one Node-coupled layer, behind a seam so a browser
 * build swaps it without touching the codec. The assembled {@link Peer} is the
 * deliverable.
 */

export * from "./errors.js";
export * as codec from "./codec/index.js";
export * as crypto from "./crypto/index.js";
export * from "./model/index.js";
export * from "./identity/index.js";
export * from "./capability/index.js";
export * from "./emit/index.js";
export * from "./store/index.js";
export * from "./handlers/index.js";
export * from "./dispatch/index.js";
export * from "./types/index.js";
export * from "./transport/index.js";
export * from "./peer.js";
