#!/usr/bin/env python3
"""Generate the §9.5 core-type-floor Ada package from the oracle floor dump.

Input  : output/type-floor-dump.json  (produced by the disposable cmd/dump-floor
         Go program against entity-core-go @ 62044c5 — types.RegisterCoreTypes +
         the validate-peer runTypeSystem registry setup).
Output : src/entity_core-protocol-type_registry.{ads,adb}

Each floor type is served at system/type/<name> as a `system/type` entity whose
data is the canonical ECF-encoded TypeDefinition payload — byte-identical to the
oracle, so validate-peer type_system _match (content_hash equality) passes 53/53.
"""
import json, sys, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
dump = json.load(open(os.path.join(ROOT, "output", "type-floor-dump.json")))
floor = sorted((t for t in dump if t["in_floor"]), key=lambda t: t["name"])
assert len(floor) == 53, f"expected 53 floor types, got {len(floor)}"

spec = '''--  entity_core-protocol-type_registry.ads — the §9.5 core-type floor (53 types).
--
--  GENERATED by tools/gen_type_registry.py from the STAMPED v7.75 cohort oracle
--  entity-core-go @ 62044c5 (types.RegisterCoreTypes + the validate-peer
--  runTypeSystem registry setup). Each floor type is served at
--  system/type/<name> as a `system/type` entity whose data is the canonical
--  ECF-encoded TypeDefinition payload — byte-identical to the oracle, so the
--  validate-peer type_system _match (content_hash equality) passes 53/53.
--  DO NOT EDIT BY HAND. Regenerate when the oracle moves (oracle-rebuild rule).

with Entity_Core.Protocol.Store;

package Entity_Core.Protocol.Type_Registry is

   --  Publish the 53 core-floor type definitions into Store under the local
   --  peer's namespace ("/" & Local & "/system/type/<name>").
   procedure Publish
     (St    : Entity_Core.Protocol.Store.Store_Access;
      Local : String);

   --  Count of floor types (for self-test).
   Floor_Count : constant := 53;

end Entity_Core.Protocol.Type_Registry;
'''

L = []
L.append('--  entity_core-protocol-type_registry.adb — GENERATED. See the .ads header.')
L.append('--  Regenerate via tools/gen_type_registry.py. DO NOT EDIT BY HAND.')
L.append('')
L.append('with Entity_Core.Bytes;')
L.append('with Entity_Core.Codec.Cbor;')
L.append('with Entity_Core.Codec.Value;')
L.append('with Entity_Core.Protocol.Entity;')
L.append('')
L.append('package body Entity_Core.Protocol.Type_Registry is')
L.append('')
L.append('   use Entity_Core.Bytes;')
L.append('')
L.append('   procedure Publish')
L.append('     (St    : Entity_Core.Protocol.Store.Store_Access;')
L.append('      Local : String)')
L.append('   is')
L.append('      use Entity_Core.Protocol.Entity;')
L.append('')
L.append('      procedure Bind_Type (Name : String; Data_Hex : String) is')
L.append('         Data : constant Entity_Core.Codec.Value.Ecf_Value :=')
L.append('           Entity_Core.Codec.Cbor.Decode (From_Hex (Data_Hex));')
L.append('         Ent  : constant Materialized_Entity := Make ("system/type", Data);')
L.append('      begin')
L.append('         St.Bind ("/" & Local & "/system/type/" & Name, Ent);')
L.append('      end Bind_Type;')
L.append('   begin')
for t in floor:
    name, hx = t["name"], t["data_hex"]
    chunks = [hx[i:i+70] for i in range(0, len(hx), 70)]
    if len(chunks) == 1:
        L.append(f'      Bind_Type ("{name}", "{hx}");')
    else:
        L.append(f'      Bind_Type ("{name}",')
        for j, c in enumerate(chunks):
            sep = ');' if j == len(chunks) - 1 else ' &'
            L.append(f'         "{c}"{sep}')
L.append('   end Publish;')
L.append('')
L.append('end Entity_Core.Protocol.Type_Registry;')
body = '\n'.join(L) + '\n'

open(os.path.join(ROOT, "src", "entity_core-protocol-type_registry.ads"), "w").write(spec)
open(os.path.join(ROOT, "src", "entity_core-protocol-type_registry.adb"), "w").write(body)
print(f"generated {len(floor)} floor types")
