/-
  Core type floor (V7 §9.5) — the 53 core type models, transcribed verbatim from
  the cohort cross-impl Go-rendered type shapes (the OCaml `type_defs_data.ml`
  override table; same source the whole cohort renders). Render-from-model: each
  is materialized to a `system/type` entity whose content_hash is computed by our
  own S2 codec, published at `/{peer}/system/type/{name}` at bootstrap. A core
  peer publishes exactly these 53; matched-if-present for anything outside.
-/
import EntityCore.Codec.Value

namespace EntityCore.TypeDefs

open EntityCore (Value)

/-- (type_name, type-model data) for all 53 core types. -/
def coreTypes : List (String × Value) := [

  ("primitive/any", .map [(.text "name", .text "primitive/any")]),
  ("primitive/bool", .map [(.text "name", .text "primitive/bool")]),
  ("primitive/bytes", .map [(.text "name", .text "primitive/bytes")]),
  ("primitive/float", .map [(.text "name", .text "primitive/float")]),
  ("primitive/int", .map [(.text "name", .text "primitive/int")]),
  ("primitive/null", .map [(.text "name", .text "primitive/null")]),
  ("primitive/string", .map [(.text "name", .text "primitive/string")]),
  ("primitive/uint", .map [(.text "name", .text "primitive/uint")]),
  ("entity", .map [(.text "name", .text "entity"), (.text "fields", .map [(.text "data", .map [(.text "type_ref", .text "primitive/any")]), (.text "type", .map [(.text "type_ref", .text "primitive/string")])])]),
  ("core/entity", .map [(.text "name", .text "core/entity"), (.text "fields", .map [(.text "content_hash", .map [(.text "type_ref", .text "system/hash")]), (.text "data", .map [(.text "type_ref", .text "primitive/any")]), (.text "type", .map [(.text "type_ref", .text "primitive/string")])])]),
  ("core/envelope", .map [(.text "name", .text "core/envelope"), (.text "fields", .map [(.text "included", .map [(.text "optional", .bool true), (.text "map_of", .map [(.text "type_ref", .text "core/entity")]), (.text "key_type", .text "system/hash")]), (.text "root", .map [(.text "type_ref", .text "core/entity")])])]),
  ("system/envelope", .map [(.text "name", .text "system/envelope"), (.text "extends", .text "core/envelope")]),
  ("system/protocol/envelope", .map [(.text "name", .text "system/protocol/envelope"), (.text "extends", .text "core/envelope")]),
  ("system/hash", .map [(.text "name", .text "system/hash"), (.text "fields", .map [(.text "digest", .map [(.text "type_ref", .text "primitive/bytes")]), (.text "format_code", .map [(.text "type_ref", .text "primitive/uint"), (.text "byte_size", .uint 1)])]), (.text "extends", .text "primitive/bytes"), (.text "layout", .array [.text "format_code", .text "digest"])]),
  ("system/peer", .map [(.text "name", .text "system/peer"), (.text "fields", .map [(.text "key_type", .map [(.text "type_ref", .text "primitive/string")]), (.text "peer_id", .map [(.text "type_ref", .text "system/peer-id")]), (.text "public_key", .map [(.text "type_ref", .text "primitive/bytes")])])]),
  ("system/peer-id", .map [(.text "name", .text "system/peer-id"), (.text "extends", .text "primitive/string")]),
  ("system/signature", .map [(.text "name", .text "system/signature"), (.text "fields", .map [(.text "algorithm", .map [(.text "type_ref", .text "primitive/string")]), (.text "signature", .map [(.text "type_ref", .text "primitive/bytes")]), (.text "signer", .map [(.text "type_ref", .text "system/hash")]), (.text "target", .map [(.text "type_ref", .text "system/hash")])])]),
  ("system/protocol/connect/authenticate", .map [(.text "name", .text "system/protocol/connect/authenticate"), (.text "fields", .map [(.text "key_type", .map [(.text "type_ref", .text "primitive/string")]), (.text "nonce", .map [(.text "type_ref", .text "primitive/bytes")]), (.text "peer_id", .map [(.text "type_ref", .text "system/peer-id")]), (.text "public_key", .map [(.text "type_ref", .text "primitive/bytes")])])]),
  ("system/protocol/connect/hello", .map [(.text "name", .text "system/protocol/connect/hello"), (.text "fields", .map [(.text "compression", .map [(.text "optional", .bool true), (.text "array_of", .map [(.text "type_ref", .text "primitive/string")])]), (.text "encryption", .map [(.text "optional", .bool true), (.text "array_of", .map [(.text "type_ref", .text "primitive/string")])]), (.text "hash_formats", .map [(.text "optional", .bool true), (.text "array_of", .map [(.text "type_ref", .text "primitive/string")])]), (.text "key_types", .map [(.text "optional", .bool true), (.text "array_of", .map [(.text "type_ref", .text "primitive/string")])]), (.text "nonce", .map [(.text "type_ref", .text "primitive/bytes")]), (.text "peer_id", .map [(.text "type_ref", .text "system/peer-id")]), (.text "protocols", .map [(.text "array_of", .map [(.text "type_ref", .text "primitive/string")])]), (.text "timestamp", .map [(.text "type_ref", .text "primitive/uint")])])]),
  ("system/protocol/error", .map [(.text "name", .text "system/protocol/error"), (.text "fields", .map [(.text "code", .map [(.text "type_ref", .text "primitive/string")]), (.text "message", .map [(.text "type_ref", .text "primitive/string"), (.text "optional", .bool true)]), (.text "rejected_marker", .map [(.text "type_ref", .text "system/hash"), (.text "optional", .bool true)])])]),
  ("system/protocol/execute", .map [(.text "name", .text "system/protocol/execute"), (.text "fields", .map [(.text "author", .map [(.text "type_ref", .text "system/hash"), (.text "optional", .bool true)]), (.text "bounds", .map [(.text "type_ref", .text "system/bounds"), (.text "optional", .bool true)]), (.text "capability", .map [(.text "type_ref", .text "system/hash"), (.text "optional", .bool true)]), (.text "deliver_to", .map [(.text "type_ref", .text "system/delivery-spec"), (.text "optional", .bool true)]), (.text "deliver_token", .map [(.text "type_ref", .text "system/hash"), (.text "optional", .bool true)]), (.text "durability_request", .map [(.text "type_ref", .text "system/durability-request"), (.text "optional", .bool true)]), (.text "operation", .map [(.text "type_ref", .text "primitive/string")]), (.text "params", .map [(.text "type_ref", .text "core/entity")]), (.text "request_id", .map [(.text "type_ref", .text "primitive/string")]), (.text "resource", .map [(.text "type_ref", .text "system/protocol/resource-target"), (.text "optional", .bool true)]), (.text "uri", .map [(.text "type_ref", .text "system/tree/path")])])]),
  ("system/protocol/execute/response", .map [(.text "name", .text "system/protocol/execute/response"), (.text "fields", .map [(.text "durability", .map [(.text "type_ref", .text "system/durability-result"), (.text "optional", .bool true)]), (.text "request_id", .map [(.text "type_ref", .text "primitive/string")]), (.text "result", .map [(.text "type_ref", .text "core/entity")]), (.text "status", .map [(.text "type_ref", .text "primitive/uint")])])]),
  ("system/protocol/resource-target", .map [(.text "name", .text "system/protocol/resource-target"), (.text "fields", .map [(.text "exclude", .map [(.text "optional", .bool true), (.text "array_of", .map [(.text "type_ref", .text "system/tree/path")])]), (.text "targets", .map [(.text "array_of", .map [(.text "type_ref", .text "system/tree/path")])])])]),
  ("system/capability/grant", .map [(.text "name", .text "system/capability/grant"), (.text "fields", .map [(.text "token", .map [(.text "type_ref", .text "system/hash")])])]),
  ("system/capability/grant-entry", .map [(.text "name", .text "system/capability/grant-entry"), (.text "fields", .map [(.text "allowances", .map [(.text "optional", .bool true), (.text "map_of", .map [(.text "type_ref", .text "primitive/any")])]), (.text "constraints", .map [(.text "optional", .bool true), (.text "map_of", .map [(.text "type_ref", .text "primitive/any")])]), (.text "handlers", .map [(.text "type_ref", .text "system/capability/path-scope")]), (.text "operations", .map [(.text "type_ref", .text "system/capability/id-scope")]), (.text "peers", .map [(.text "type_ref", .text "system/capability/id-scope"), (.text "optional", .bool true)]), (.text "resources", .map [(.text "type_ref", .text "system/capability/path-scope")])])]),
  ("system/capability/id-scope", .map [(.text "name", .text "system/capability/id-scope"), (.text "fields", .map [(.text "exclude", .map [(.text "optional", .bool true), (.text "array_of", .map [(.text "type_ref", .text "primitive/string")])]), (.text "include", .map [(.text "array_of", .map [(.text "type_ref", .text "primitive/string")])])])]),
  ("system/capability/path-scope", .map [(.text "name", .text "system/capability/path-scope"), (.text "fields", .map [(.text "exclude", .map [(.text "optional", .bool true), (.text "array_of", .map [(.text "type_ref", .text "system/tree/path")])]), (.text "include", .map [(.text "array_of", .map [(.text "type_ref", .text "system/tree/path")])])])]),
  ("system/capability/request", .map [(.text "name", .text "system/capability/request"), (.text "fields", .map [(.text "grants", .map [(.text "array_of", .map [(.text "type_ref", .text "system/capability/grant-entry")])]), (.text "ttl_ms", .map [(.text "type_ref", .text "primitive/uint"), (.text "optional", .bool true)])])]),
  ("system/capability/revocation", .map [(.text "name", .text "system/capability/revocation"), (.text "fields", .map [(.text "reason", .map [(.text "type_ref", .text "primitive/string"), (.text "optional", .bool true)]), (.text "revoked_at", .map [(.text "type_ref", .text "primitive/uint")]), (.text "token", .map [(.text "type_ref", .text "system/hash")])])]),
  ("system/capability/revoke-request", .map [(.text "name", .text "system/capability/revoke-request"), (.text "fields", .map [(.text "reason", .map [(.text "type_ref", .text "primitive/string"), (.text "optional", .bool true)]), (.text "token", .map [(.text "type_ref", .text "system/hash")])])]),
  ("system/capability/delegate-request", .map [(.text "name", .text "system/capability/delegate-request"), (.text "fields", .map [(.text "grants", .map [(.text "array_of", .map [(.text "type_ref", .text "system/capability/grant-entry")])]), (.text "parent", .map [(.text "type_ref", .text "system/hash")]), (.text "ttl_ms", .map [(.text "type_ref", .text "primitive/uint"), (.text "optional", .bool true)])])]),
  ("system/capability/delegation-caveats", .map [(.text "name", .text "system/capability/delegation-caveats"), (.text "fields", .map [(.text "max_delegation_depth", .map [(.text "type_ref", .text "primitive/uint"), (.text "optional", .bool true)]), (.text "max_delegation_ttl", .map [(.text "type_ref", .text "primitive/uint"), (.text "optional", .bool true)]), (.text "no_delegation", .map [(.text "type_ref", .text "primitive/bool"), (.text "optional", .bool true)])])]),
  ("system/capability/policy-entry", .map [(.text "name", .text "system/capability/policy-entry"), (.text "fields", .map [(.text "grants", .map [(.text "array_of", .map [(.text "type_ref", .text "system/capability/grant-entry")])]), (.text "notes", .map [(.text "type_ref", .text "primitive/string"), (.text "optional", .bool true)]), (.text "peer_pattern", .map [(.text "type_ref", .text "primitive/string")]), (.text "ttl_ms", .map [(.text "type_ref", .text "primitive/uint"), (.text "optional", .bool true)])])]),
  ("system/capability/token", .map [(.text "name", .text "system/capability/token"), (.text "fields", .map [(.text "created_at", .map [(.text "type_ref", .text "primitive/uint")]), (.text "delegation_caveats", .map [(.text "type_ref", .text "system/capability/delegation-caveats"), (.text "optional", .bool true)]), (.text "expires_at", .map [(.text "type_ref", .text "primitive/uint"), (.text "optional", .bool true)]), (.text "grantee", .map [(.text "type_ref", .text "system/hash")]), (.text "granter", .map [(.text "union_of", .array [.map [(.text "type_ref", .text "system/hash")], .map [(.text "type_ref", .text "system/capability/multi-granter")]])]), (.text "grants", .map [(.text "array_of", .map [(.text "type_ref", .text "system/capability/grant-entry")])]), (.text "not_before", .map [(.text "type_ref", .text "primitive/uint"), (.text "optional", .bool true)]), (.text "parent", .map [(.text "type_ref", .text "system/hash"), (.text "optional", .bool true)]), (.text "resource_limits", .map [(.text "type_ref", .text "system/resource-limits"), (.text "optional", .bool true)])])]),
  ("system/capability/multi-granter", .map [(.text "name", .text "system/capability/multi-granter"), (.text "fields", .map [(.text "signers", .map [(.text "array_of", .map [(.text "type_ref", .text "system/hash")])]), (.text "threshold", .map [(.text "type_ref", .text "primitive/uint")])])]),
  ("system/handler", .map [(.text "name", .text "system/handler"), (.text "fields", .map [(.text "expression_path", .map [(.text "type_ref", .text "system/tree/path"), (.text "optional", .bool true)]), (.text "interface", .map [(.text "type_ref", .text "system/tree/path")]), (.text "internal_scope", .map [(.text "optional", .bool true), (.text "array_of", .map [(.text "type_ref", .text "system/capability/grant-entry")])]), (.text "max_scope", .map [(.text "optional", .bool true), (.text "array_of", .map [(.text "type_ref", .text "system/capability/grant-entry")])])])]),
  ("system/handler/interface", .map [(.text "name", .text "system/handler/interface"), (.text "fields", .map [(.text "name", .map [(.text "type_ref", .text "primitive/string")]), (.text "operations", .map [(.text "map_of", .map [(.text "type_ref", .text "system/handler/operation-spec")])]), (.text "pattern", .map [(.text "type_ref", .text "system/tree/path")])])]),
  ("system/handler/manifest", .map [(.text "name", .text "system/handler/manifest"), (.text "fields", .map [(.text "expression_path", .map [(.text "type_ref", .text "system/tree/path"), (.text "optional", .bool true)]), (.text "internal_scope", .map [(.text "optional", .bool true), (.text "array_of", .map [(.text "type_ref", .text "system/capability/grant-entry")])]), (.text "max_scope", .map [(.text "optional", .bool true), (.text "array_of", .map [(.text "type_ref", .text "system/capability/grant-entry")])]), (.text "name", .map [(.text "type_ref", .text "primitive/string")]), (.text "operations", .map [(.text "map_of", .map [(.text "type_ref", .text "system/handler/operation-spec")])]), (.text "pattern", .map [(.text "type_ref", .text "system/tree/path")])]), (.text "extends", .text "system/handler/interface")]),
  ("system/handler/operation-spec", .map [(.text "name", .text "system/handler/operation-spec"), (.text "fields", .map [(.text "input_type", .map [(.text "type_ref", .text "system/type/name"), (.text "optional", .bool true)]), (.text "output_type", .map [(.text "type_ref", .text "system/type/name"), (.text "optional", .bool true)])])]),
  ("system/handler/register-request", .map [(.text "name", .text "system/handler/register-request"), (.text "fields", .map [(.text "manifest", .map [(.text "type_ref", .text "system/handler/manifest")]), (.text "requested_scope", .map [(.text "optional", .bool true), (.text "array_of", .map [(.text "type_ref", .text "system/capability/grant-entry")])]), (.text "types", .map [(.text "optional", .bool true), (.text "map_of", .map [(.text "type_ref", .text "system/type")])])])]),
  ("system/handler/register-result", .map [(.text "name", .text "system/handler/register-result"), (.text "fields", .map [(.text "grant", .map [(.text "type_ref", .text "system/capability/token")]), (.text "pattern", .map [(.text "type_ref", .text "system/tree/path")])])]),
  ("system/tree/get-request", .map [(.text "name", .text "system/tree/get-request"), (.text "fields", .map [(.text "limit", .map [(.text "type_ref", .text "primitive/uint"), (.text "optional", .bool true)]), (.text "mode", .map [(.text "type_ref", .text "primitive/string"), (.text "optional", .bool true)]), (.text "offset", .map [(.text "type_ref", .text "primitive/uint"), (.text "optional", .bool true)]), (.text "tree_id", .map [(.text "type_ref", .text "primitive/string"), (.text "optional", .bool true)])])]),
  ("system/tree/put-request", .map [(.text "name", .text "system/tree/put-request"), (.text "fields", .map [(.text "entity", .map [(.text "type_ref", .text "core/entity"), (.text "optional", .bool true)]), (.text "expected_hash", .map [(.text "type_ref", .text "system/hash"), (.text "optional", .bool true)]), (.text "tree_id", .map [(.text "type_ref", .text "primitive/string"), (.text "optional", .bool true)])])]),
  ("system/tree/listing", .map [(.text "name", .text "system/tree/listing"), (.text "fields", .map [(.text "count", .map [(.text "type_ref", .text "primitive/uint")]), (.text "entries", .map [(.text "map_of", .map [(.text "type_ref", .text "system/tree/listing-entry")])]), (.text "next_page", .map [(.text "type_ref", .text "system/hash"), (.text "optional", .bool true)]), (.text "offset", .map [(.text "type_ref", .text "primitive/uint")]), (.text "path", .map [(.text "type_ref", .text "system/tree/path")])])]),
  ("system/tree/listing-entry", .map [(.text "name", .text "system/tree/listing-entry"), (.text "fields", .map [(.text "has_children", .map [(.text "type_ref", .text "primitive/bool")]), (.text "hash", .map [(.text "type_ref", .text "system/hash"), (.text "optional", .bool true)])])]),
  ("system/tree/path", .map [(.text "name", .text "system/tree/path"), (.text "extends", .text "primitive/string")]),
  ("system/type", .map [(.text "name", .text "system/type"), (.text "fields", .map [(.text "extends", .map [(.text "type_ref", .text "system/type/name"), (.text "optional", .bool true)]), (.text "fields", .map [(.text "optional", .bool true), (.text "map_of", .map [(.text "type_ref", .text "system/type/field-spec")])]), (.text "layout", .map [(.text "optional", .bool true), (.text "array_of", .map [(.text "type_ref", .text "primitive/string")])]), (.text "name", .map [(.text "type_ref", .text "system/type/name")]), (.text "type_args", .map [(.text "optional", .bool true), (.text "map_of", .map [(.text "type_ref", .text "system/type/name")])]), (.text "type_params", .map [(.text "optional", .bool true), (.text "array_of", .map [(.text "type_ref", .text "primitive/string")])])])]),
  ("system/type/field-spec", .map [(.text "name", .text "system/type/field-spec"), (.text "fields", .map [(.text "array_of", .map [(.text "type_ref", .text "system/type/field-spec"), (.text "optional", .bool true)]), (.text "byte_size", .map [(.text "type_ref", .text "primitive/uint"), (.text "optional", .bool true)]), (.text "constraints", .map [(.text "optional", .bool true), (.text "array_of", .map [(.text "type_ref", .text "core/entity")])]), (.text "default", .map [(.text "type_ref", .text "primitive/any"), (.text "optional", .bool true)]), (.text "key_type", .map [(.text "type_ref", .text "system/type/name"), (.text "optional", .bool true)]), (.text "map_of", .map [(.text "type_ref", .text "system/type/field-spec"), (.text "optional", .bool true)]), (.text "optional", .map [(.text "type_ref", .text "primitive/bool"), (.text "optional", .bool true)]), (.text "type_args", .map [(.text "optional", .bool true), (.text "map_of", .map [(.text "type_ref", .text "system/type/name")])]), (.text "type_param", .map [(.text "type_ref", .text "primitive/string"), (.text "optional", .bool true)]), (.text "type_ref", .map [(.text "type_ref", .text "system/type/name"), (.text "optional", .bool true)]), (.text "union_of", .map [(.text "optional", .bool true), (.text "array_of", .map [(.text "type_ref", .text "system/type/field-spec")])])])]),
  ("system/type/name", .map [(.text "name", .text "system/type/name"), (.text "extends", .text "primitive/string")]),
  ("system/bounds", .map [(.text "name", .text "system/bounds"), (.text "fields", .map [(.text "budget", .map [(.text "type_ref", .text "primitive/uint"), (.text "optional", .bool true)]), (.text "cascade_depth", .map [(.text "type_ref", .text "primitive/uint"), (.text "optional", .bool true)]), (.text "chain_id", .map [(.text "type_ref", .text "primitive/string"), (.text "optional", .bool true)]), (.text "parent_chain_id", .map [(.text "type_ref", .text "primitive/string"), (.text "optional", .bool true)]), (.text "ttl", .map [(.text "type_ref", .text "primitive/uint"), (.text "optional", .bool true)]), (.text "visited", .map [(.text "optional", .bool true), (.text "array_of", .map [(.text "type_ref", .text "system/tree/path")])])])]),
  ("system/resource-limits", .map [(.text "name", .text "system/resource-limits"), (.text "fields", .map [(.text "max_budget", .map [(.text "type_ref", .text "primitive/uint"), (.text "optional", .bool true)]), (.text "max_ttl", .map [(.text "type_ref", .text "primitive/uint"), (.text "optional", .bool true)]), (.text "max_visited_length", .map [(.text "type_ref", .text "primitive/uint"), (.text "optional", .bool true)])])]),
  ("system/delivery-spec", .map [(.text "name", .text "system/delivery-spec"), (.text "fields", .map [(.text "operation", .map [(.text "type_ref", .text "primitive/string")]), (.text "uri", .map [(.text "type_ref", .text "system/tree/path")])])]),
  ("system/deletion-marker", .map [(.text "name", .text "system/deletion-marker")])
]

end EntityCore.TypeDefs
