;;;; type-defs-data.lisp — GENERATED from the shared test-vectors
;;;; type-registry-shapes.json (the cross-impl Go-rendered type model).
;;;; The in-code core-type override table (render-from-model design).
;;;; 53 core types per V7 §9.5. Regenerate with tools/gen-typedefs.py on a
;;;; V7 bump; diffed byte-for-byte against type-registry-vectors-v1 in
;;;; test/type-registry.lisp.

(in-package #:entity-core/peer)

;; (type-name . data-cbor-map) for each of the 53 core types (§9.5). The data
;; map is the `data' of a `system/type' entity; make-entity computes its hash.
(defparameter +core-type-models+
  (list
    (cons "primitive/any" (map-of "name" "primitive/any"))
    (cons "primitive/bool" (map-of "name" "primitive/bool"))
    (cons "primitive/bytes" (map-of "name" "primitive/bytes"))
    (cons "primitive/float" (map-of "name" "primitive/float"))
    (cons "primitive/int" (map-of "name" "primitive/int"))
    (cons "primitive/null" (map-of "name" "primitive/null"))
    (cons "primitive/string" (map-of "name" "primitive/string"))
    (cons "primitive/uint" (map-of "name" "primitive/uint"))
    (cons "entity" (map-of "name" "entity" "fields" (map-of "data" (map-of "type_ref" "primitive/any") "type" (map-of "type_ref" "primitive/string"))))
    (cons "core/entity" (map-of "name" "core/entity" "fields" (map-of "content_hash" (map-of "type_ref" "system/hash") "data" (map-of "type_ref" "primitive/any") "type" (map-of "type_ref" "primitive/string"))))
    (cons "core/envelope" (map-of "name" "core/envelope" "fields" (map-of "included" (map-of "optional" :true "map_of" (map-of "type_ref" "core/entity") "key_type" "system/hash") "root" (map-of "type_ref" "core/entity"))))
    (cons "system/envelope" (map-of "name" "system/envelope" "extends" "core/envelope"))
    (cons "system/protocol/envelope" (map-of "name" "system/protocol/envelope" "extends" "core/envelope"))
    (cons "system/hash" (map-of "name" "system/hash" "fields" (map-of "digest" (map-of "type_ref" "primitive/bytes") "format_code" (map-of "type_ref" "primitive/uint" "byte_size" 1)) "extends" "primitive/bytes" "layout" (list "format_code" "digest")))
    (cons "system/peer" (map-of "name" "system/peer" "fields" (map-of "key_type" (map-of "type_ref" "primitive/string") "peer_id" (map-of "type_ref" "system/peer-id") "public_key" (map-of "type_ref" "primitive/bytes"))))
    (cons "system/peer-id" (map-of "name" "system/peer-id" "extends" "primitive/string"))
    (cons "system/signature" (map-of "name" "system/signature" "fields" (map-of "algorithm" (map-of "type_ref" "primitive/string") "signature" (map-of "type_ref" "primitive/bytes") "signer" (map-of "type_ref" "system/hash") "target" (map-of "type_ref" "system/hash"))))
    (cons "system/protocol/connect/authenticate" (map-of "name" "system/protocol/connect/authenticate" "fields" (map-of "key_type" (map-of "type_ref" "primitive/string") "nonce" (map-of "type_ref" "primitive/bytes") "peer_id" (map-of "type_ref" "system/peer-id") "public_key" (map-of "type_ref" "primitive/bytes"))))
    (cons "system/protocol/connect/hello" (map-of "name" "system/protocol/connect/hello" "fields" (map-of "compression" (map-of "optional" :true "array_of" (map-of "type_ref" "primitive/string")) "encryption" (map-of "optional" :true "array_of" (map-of "type_ref" "primitive/string")) "hash_formats" (map-of "optional" :true "array_of" (map-of "type_ref" "primitive/string")) "key_types" (map-of "optional" :true "array_of" (map-of "type_ref" "primitive/string")) "nonce" (map-of "type_ref" "primitive/bytes") "peer_id" (map-of "type_ref" "system/peer-id") "protocols" (map-of "array_of" (map-of "type_ref" "primitive/string")) "timestamp" (map-of "type_ref" "primitive/uint"))))
    (cons "system/protocol/error" (map-of "name" "system/protocol/error" "fields" (map-of "code" (map-of "type_ref" "primitive/string") "message" (map-of "type_ref" "primitive/string" "optional" :true) "rejected_marker" (map-of "type_ref" "system/hash" "optional" :true))))
    (cons "system/protocol/execute" (map-of "name" "system/protocol/execute" "fields" (map-of "author" (map-of "type_ref" "system/hash" "optional" :true) "bounds" (map-of "type_ref" "system/bounds" "optional" :true) "capability" (map-of "type_ref" "system/hash" "optional" :true) "deliver_to" (map-of "type_ref" "system/delivery-spec" "optional" :true) "deliver_token" (map-of "type_ref" "system/hash" "optional" :true) "durability_request" (map-of "type_ref" "system/durability-request" "optional" :true) "operation" (map-of "type_ref" "primitive/string") "params" (map-of "type_ref" "core/entity") "request_id" (map-of "type_ref" "primitive/string") "resource" (map-of "type_ref" "system/protocol/resource-target" "optional" :true) "uri" (map-of "type_ref" "system/tree/path"))))
    (cons "system/protocol/execute/response" (map-of "name" "system/protocol/execute/response" "fields" (map-of "durability" (map-of "type_ref" "system/durability-result" "optional" :true) "request_id" (map-of "type_ref" "primitive/string") "result" (map-of "type_ref" "core/entity") "status" (map-of "type_ref" "primitive/uint"))))
    (cons "system/protocol/resource-target" (map-of "name" "system/protocol/resource-target" "fields" (map-of "exclude" (map-of "optional" :true "array_of" (map-of "type_ref" "system/tree/path")) "targets" (map-of "array_of" (map-of "type_ref" "system/tree/path")))))
    (cons "system/capability/grant" (map-of "name" "system/capability/grant" "fields" (map-of "token" (map-of "type_ref" "system/hash"))))
    (cons "system/capability/grant-entry" (map-of "name" "system/capability/grant-entry" "fields" (map-of "allowances" (map-of "optional" :true "map_of" (map-of "type_ref" "primitive/any")) "constraints" (map-of "optional" :true "map_of" (map-of "type_ref" "primitive/any")) "handlers" (map-of "type_ref" "system/capability/path-scope") "operations" (map-of "type_ref" "system/capability/id-scope") "peers" (map-of "type_ref" "system/capability/id-scope" "optional" :true) "resources" (map-of "type_ref" "system/capability/path-scope"))))
    (cons "system/capability/id-scope" (map-of "name" "system/capability/id-scope" "fields" (map-of "exclude" (map-of "optional" :true "array_of" (map-of "type_ref" "primitive/string")) "include" (map-of "array_of" (map-of "type_ref" "primitive/string")))))
    (cons "system/capability/path-scope" (map-of "name" "system/capability/path-scope" "fields" (map-of "exclude" (map-of "optional" :true "array_of" (map-of "type_ref" "system/tree/path")) "include" (map-of "array_of" (map-of "type_ref" "system/tree/path")))))
    (cons "system/capability/request" (map-of "name" "system/capability/request" "fields" (map-of "grants" (map-of "array_of" (map-of "type_ref" "system/capability/grant-entry")) "ttl_ms" (map-of "type_ref" "primitive/uint" "optional" :true))))
    (cons "system/capability/revocation" (map-of "name" "system/capability/revocation" "fields" (map-of "reason" (map-of "type_ref" "primitive/string" "optional" :true) "revoked_at" (map-of "type_ref" "primitive/uint") "token" (map-of "type_ref" "system/hash"))))
    (cons "system/capability/revoke-request" (map-of "name" "system/capability/revoke-request" "fields" (map-of "reason" (map-of "type_ref" "primitive/string" "optional" :true) "token" (map-of "type_ref" "system/hash"))))
    (cons "system/capability/delegate-request" (map-of "name" "system/capability/delegate-request" "fields" (map-of "grants" (map-of "array_of" (map-of "type_ref" "system/capability/grant-entry")) "parent" (map-of "type_ref" "system/hash") "ttl_ms" (map-of "type_ref" "primitive/uint" "optional" :true))))
    (cons "system/capability/delegation-caveats" (map-of "name" "system/capability/delegation-caveats" "fields" (map-of "max_delegation_depth" (map-of "type_ref" "primitive/uint" "optional" :true) "max_delegation_ttl" (map-of "type_ref" "primitive/uint" "optional" :true) "no_delegation" (map-of "type_ref" "primitive/bool" "optional" :true))))
    (cons "system/capability/policy-entry" (map-of "name" "system/capability/policy-entry" "fields" (map-of "grants" (map-of "array_of" (map-of "type_ref" "system/capability/grant-entry")) "notes" (map-of "type_ref" "primitive/string" "optional" :true) "peer_pattern" (map-of "type_ref" "primitive/string") "ttl_ms" (map-of "type_ref" "primitive/uint" "optional" :true))))
    (cons "system/capability/token" (map-of "name" "system/capability/token" "fields" (map-of "created_at" (map-of "type_ref" "primitive/uint") "delegation_caveats" (map-of "type_ref" "system/capability/delegation-caveats" "optional" :true) "expires_at" (map-of "type_ref" "primitive/uint" "optional" :true) "grantee" (map-of "type_ref" "system/hash") "granter" (map-of "union_of" (list (map-of "type_ref" "system/hash") (map-of "type_ref" "system/capability/multi-granter"))) "grants" (map-of "array_of" (map-of "type_ref" "system/capability/grant-entry")) "not_before" (map-of "type_ref" "primitive/uint" "optional" :true) "parent" (map-of "type_ref" "system/hash" "optional" :true) "resource_limits" (map-of "type_ref" "system/resource-limits" "optional" :true))))
    (cons "system/capability/multi-granter" (map-of "name" "system/capability/multi-granter" "fields" (map-of "signers" (map-of "array_of" (map-of "type_ref" "system/hash")) "threshold" (map-of "type_ref" "primitive/uint"))))
    (cons "system/handler" (map-of "name" "system/handler" "fields" (map-of "expression_path" (map-of "type_ref" "system/tree/path" "optional" :true) "interface" (map-of "type_ref" "system/tree/path") "internal_scope" (map-of "optional" :true "array_of" (map-of "type_ref" "system/capability/grant-entry")) "max_scope" (map-of "optional" :true "array_of" (map-of "type_ref" "system/capability/grant-entry")))))
    (cons "system/handler/interface" (map-of "name" "system/handler/interface" "fields" (map-of "name" (map-of "type_ref" "primitive/string") "operations" (map-of "map_of" (map-of "type_ref" "system/handler/operation-spec")) "pattern" (map-of "type_ref" "system/tree/path"))))
    (cons "system/handler/manifest" (map-of "name" "system/handler/manifest" "fields" (map-of "expression_path" (map-of "type_ref" "system/tree/path" "optional" :true) "internal_scope" (map-of "optional" :true "array_of" (map-of "type_ref" "system/capability/grant-entry")) "max_scope" (map-of "optional" :true "array_of" (map-of "type_ref" "system/capability/grant-entry")) "name" (map-of "type_ref" "primitive/string") "operations" (map-of "map_of" (map-of "type_ref" "system/handler/operation-spec")) "pattern" (map-of "type_ref" "system/tree/path")) "extends" "system/handler/interface"))
    (cons "system/handler/operation-spec" (map-of "name" "system/handler/operation-spec" "fields" (map-of "input_type" (map-of "type_ref" "system/type/name" "optional" :true) "output_type" (map-of "type_ref" "system/type/name" "optional" :true))))
    (cons "system/handler/register-request" (map-of "name" "system/handler/register-request" "fields" (map-of "manifest" (map-of "type_ref" "system/handler/manifest") "requested_scope" (map-of "optional" :true "array_of" (map-of "type_ref" "system/capability/grant-entry")) "types" (map-of "optional" :true "map_of" (map-of "type_ref" "system/type")))))
    (cons "system/handler/register-result" (map-of "name" "system/handler/register-result" "fields" (map-of "grant" (map-of "type_ref" "system/capability/token") "pattern" (map-of "type_ref" "system/tree/path"))))
    (cons "system/tree/get-request" (map-of "name" "system/tree/get-request" "fields" (map-of "limit" (map-of "type_ref" "primitive/uint" "optional" :true) "mode" (map-of "type_ref" "primitive/string" "optional" :true) "offset" (map-of "type_ref" "primitive/uint" "optional" :true) "tree_id" (map-of "type_ref" "primitive/string" "optional" :true))))
    (cons "system/tree/put-request" (map-of "name" "system/tree/put-request" "fields" (map-of "entity" (map-of "type_ref" "core/entity" "optional" :true) "expected_hash" (map-of "type_ref" "system/hash" "optional" :true) "tree_id" (map-of "type_ref" "primitive/string" "optional" :true))))
    (cons "system/tree/listing" (map-of "name" "system/tree/listing" "fields" (map-of "count" (map-of "type_ref" "primitive/uint") "entries" (map-of "map_of" (map-of "type_ref" "system/tree/listing-entry")) "next_page" (map-of "type_ref" "system/hash" "optional" :true) "offset" (map-of "type_ref" "primitive/uint") "path" (map-of "type_ref" "system/tree/path"))))
    (cons "system/tree/listing-entry" (map-of "name" "system/tree/listing-entry" "fields" (map-of "has_children" (map-of "type_ref" "primitive/bool") "hash" (map-of "type_ref" "system/hash" "optional" :true))))
    (cons "system/tree/path" (map-of "name" "system/tree/path" "extends" "primitive/string"))
    (cons "system/type" (map-of "name" "system/type" "fields" (map-of "extends" (map-of "type_ref" "system/type/name" "optional" :true) "fields" (map-of "optional" :true "map_of" (map-of "type_ref" "system/type/field-spec")) "layout" (map-of "optional" :true "array_of" (map-of "type_ref" "primitive/string")) "name" (map-of "type_ref" "system/type/name") "type_args" (map-of "optional" :true "map_of" (map-of "type_ref" "system/type/name")) "type_params" (map-of "optional" :true "array_of" (map-of "type_ref" "primitive/string")))))
    (cons "system/type/field-spec" (map-of "name" "system/type/field-spec" "fields" (map-of "array_of" (map-of "type_ref" "system/type/field-spec" "optional" :true) "byte_size" (map-of "type_ref" "primitive/uint" "optional" :true) "constraints" (map-of "optional" :true "array_of" (map-of "type_ref" "core/entity")) "default" (map-of "type_ref" "primitive/any" "optional" :true) "key_type" (map-of "type_ref" "system/type/name" "optional" :true) "map_of" (map-of "type_ref" "system/type/field-spec" "optional" :true) "optional" (map-of "type_ref" "primitive/bool" "optional" :true) "type_args" (map-of "optional" :true "map_of" (map-of "type_ref" "system/type/name")) "type_param" (map-of "type_ref" "primitive/string" "optional" :true) "type_ref" (map-of "type_ref" "system/type/name" "optional" :true) "union_of" (map-of "optional" :true "array_of" (map-of "type_ref" "system/type/field-spec")))))
    (cons "system/type/name" (map-of "name" "system/type/name" "extends" "primitive/string"))
    (cons "system/bounds" (map-of "name" "system/bounds" "fields" (map-of "budget" (map-of "type_ref" "primitive/uint" "optional" :true) "cascade_depth" (map-of "type_ref" "primitive/uint" "optional" :true) "chain_id" (map-of "type_ref" "primitive/string" "optional" :true) "parent_chain_id" (map-of "type_ref" "primitive/string" "optional" :true) "ttl" (map-of "type_ref" "primitive/uint" "optional" :true) "visited" (map-of "optional" :true "array_of" (map-of "type_ref" "system/tree/path")))))
    (cons "system/resource-limits" (map-of "name" "system/resource-limits" "fields" (map-of "max_budget" (map-of "type_ref" "primitive/uint" "optional" :true) "max_ttl" (map-of "type_ref" "primitive/uint" "optional" :true) "max_visited_length" (map-of "type_ref" "primitive/uint" "optional" :true))))
    (cons "system/delivery-spec" (map-of "name" "system/delivery-spec" "fields" (map-of "operation" (map-of "type_ref" "primitive/string") "uri" (map-of "type_ref" "system/tree/path"))))
    (cons "system/deletion-marker" (map-of "name" "system/deletion-marker"))
    ))

