#!/usr/bin/env python3
# gen-corpus-header.py — host-side generator (container has no python3).
#
# Extract (id, kind, canonical-hex) from the pinned ECF conformance corpus's
# human source-of-truth (.diag) and emit a C header the in-container differential
# harness (tools/diff-harness.c) compiles against. We deliberately read only the
# three fields the L2 bare-value differential needs — the golden canonical bytes
# are the ground truth, fed through our asm `ec_encode_bare_value` and compared to
# themselves (encode_equal) or asserted-rejected (decode_reject). NOT a codec:
# a dumb line extractor over the one-line-per-vector .diag. The .cbor artifact
# stays the normative build input; this only mirrors its golden bytes for the harness.
import re, sys, pathlib

DIAG = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(
    __file__).resolve().parents[3] / "shared/test-vectors/v0.8.0/conformance-vectors-v1.diag"
OUT = pathlib.Path(sys.argv[2]) if len(sys.argv) > 2 else pathlib.Path(
    __file__).resolve().parent / "corpus_vectors.h"

line_re = re.compile(
    r'"id"\s*:\s*"(?P<id>[^"]+)".*?'
    r'"kind"\s*:\s*"(?P<kind>[^"]+)".*?'
    r"\"canonical\"\s*:\s*h'(?P<hex>[0-9a-fA-F]*)'")

vectors = []
for line in DIAG.read_text().splitlines():
    m = line_re.search(line)
    if not m:
        continue
    vid, kind, hx = m.group("id"), m.group("kind"), m.group("hex").lower()
    assert len(hx) % 2 == 0, f"odd hex for {vid}"
    cat = vid.split(".")[0]
    vectors.append((vid, cat, kind, hx))

assert len(vectors) == 71, f"expected 71 vectors, got {len(vectors)}"

lines = []
lines.append("/* GENERATED by tools/gen-corpus-header.py from the pinned .diag. DO NOT EDIT. */")
lines.append("/* Each vector: id, category, reject(1=decode_reject/0=encode_equal), byte len, bytes. */")
lines.append("#ifndef CORPUS_VECTORS_H")
lines.append("#define CORPUS_VECTORS_H")
lines.append("#include <stddef.h>")
lines.append("#include <stdint.h>")
lines.append("typedef struct { const char *id; const char *cat; int reject; size_t len; const uint8_t *bytes; } corpus_vec_t;")
for i, (vid, cat, kind, hx) in enumerate(vectors):
    reject = 1 if kind == "decode_reject" else 0
    body = "".join(f"\\x{hx[j:j+2]}" for j in range(0, len(hx), 2)) or ""
    lines.append(f'static const uint8_t v_bytes_{i}[] = "{body}";')
lines.append("static const corpus_vec_t CORPUS_VECTORS[] = {")
for i, (vid, cat, kind, hx) in enumerate(vectors):
    reject = 1 if kind == "decode_reject" else 0
    nbytes = len(hx) // 2
    lines.append(f'  {{ "{vid}", "{cat}", {reject}, {nbytes}, v_bytes_{i} }},')
lines.append("};")
lines.append(f"#define CORPUS_VECTOR_COUNT {len(vectors)}")
lines.append("#endif")

OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT} ({len(vectors)} vectors)")
