# Conan recipe for entity-core-protocol-cpp (S5 packaging, A-CPP-016).
#
# AUTHORED + version-pinned (`entity-core-protocol/0.1.0`), NOT pushed to any
# conan registry (conancenter or a private remote). Publishing is an operator
# action (lifecycle Publishing). Build the package locally from the peer tree:
#
#     conan create packaging/conan --version 0.1.0
#
# conan is the second of the two decentralized C++ package managers the slate
# names (row 3); a conan recipe + the vcpkg port + the CMake find_package package
# are the three parallel distribution surfaces (C++ has no central registry).
#
# The `version` is dotted-numeric (0.1.0); the `-pre` pre-release marker lives in
# CHANGELOG/README (A-CPP-015). On a real publish, `set repository_url` in
# profile.toml [publishing] and switch `exports_sources`/the source() method to a
# tagged-release fetch.
#
# SPDX-License-Identifier: Apache-2.0

from conan import ConanFile
from conan.tools.cmake import CMake, CMakeToolchain, CMakeDeps, cmake_layout
from conan.tools.files import copy
import os


class EntityCoreProtocolConan(ConanFile):
    name = "entity-core-protocol"
    version = "0.1.0"  # numeric; -pre marker in CHANGELOG/README (A-CPP-015)
    description = (
        "Entity Core protocol (V7) core peer — native C++23 ECF codec + "
        "Ed25519/SHA-256 (libsodium). Generated by entity-core-keystone /entity-rosetta."
    )
    license = "Apache-2.0"
    homepage = "https://github.com/entity-systems/entity-core-keystone"
    url = homepage
    topics = ("entity-core", "protocol", "cbor", "ecf", "ed25519", "keystone")

    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = {"shared": False, "fPIC": True}

    # In-repo: the recipe builds the peer tree two dirs up. On publish, replace
    # exports_sources with a source() that fetches the tagged release tarball.
    exports_sources = "../../*"

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def configure(self):
        if self.options.shared:
            self.options.rm_safe("fPIC")
        # C++23 — std::expected forces the bump (A-CPP-009).
        self.settings.compiler.cppstd = "23"

    def requirements(self):
        # libsodium is the single runtime dependency (Ed25519 + SHA-256).
        self.requires("libsodium/1.0.20")

    def layout(self):
        cmake_layout(self, src_folder=os.path.join("..", ".."))

    def generate(self):
        CMakeDeps(self).generate()
        tc = CMakeToolchain(self)
        tc.variables["EC_SANITIZE"] = "OFF"
        tc.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()
        copy(self, "LICENSE",
             src=self.source_folder,
             dst=os.path.join(self.package_folder, "licenses"))

    def package_info(self):
        self.cpp_info.set_property("cmake_file_name", "EntityCoreProtocol")
        self.cpp_info.set_property("cmake_target_name", "entity_core::protocol")
        self.cpp_info.libs = ["entity_core_protocol"]
        if self.settings.os in ("Linux", "FreeBSD"):
            self.cpp_info.system_libs = ["pthread"]
