defmodule EntityCore.TypeDefsData do
  @moduledoc """
  GENERATED from test-vectors/v0.8.0/type-registry-shapes.json (the cross-impl
  Go-rendered type model) — the in-code core-type override table
  (render-from-model design). 53 core types per V7 §9.5. Regenerate with
  `tools/gen_typedefs.py` on a V7 bump; diffed byte-for-byte against
  type-registry-vectors-v1 in test/type_registry_test.exs.
  """

  @doc "The 53 core types as `{name, data}` tuples (data = model-form map)."
  @spec core_types() :: [{String.t(), map()}]
  def core_types do
    [
      {"primitive/any", %{"name" => "primitive/any"}},
      {"primitive/bool", %{"name" => "primitive/bool"}},
      {"primitive/bytes", %{"name" => "primitive/bytes"}},
      {"primitive/float", %{"name" => "primitive/float"}},
      {"primitive/int", %{"name" => "primitive/int"}},
      {"primitive/null", %{"name" => "primitive/null"}},
      {"primitive/string", %{"name" => "primitive/string"}},
      {"primitive/uint", %{"name" => "primitive/uint"}},
      {"entity", %{"name" => "entity", "fields" => %{"data" => %{"type_ref" => "primitive/any"}, "type" => %{"type_ref" => "primitive/string"}}}},
      {"core/entity", %{"name" => "core/entity", "fields" => %{"content_hash" => %{"type_ref" => "system/hash"}, "data" => %{"type_ref" => "primitive/any"}, "type" => %{"type_ref" => "primitive/string"}}}},
      {"core/envelope", %{"name" => "core/envelope", "fields" => %{"included" => %{"optional" => true, "map_of" => %{"type_ref" => "core/entity"}, "key_type" => "system/hash"}, "root" => %{"type_ref" => "core/entity"}}}},
      {"system/envelope", %{"name" => "system/envelope", "extends" => "core/envelope"}},
      {"system/protocol/envelope", %{"name" => "system/protocol/envelope", "extends" => "core/envelope"}},
      {"system/hash", %{"name" => "system/hash", "fields" => %{"digest" => %{"type_ref" => "primitive/bytes"}, "format_code" => %{"type_ref" => "primitive/uint", "byte_size" => 1}}, "extends" => "primitive/bytes", "layout" => ["format_code", "digest"]}},
      {"system/peer", %{"name" => "system/peer", "fields" => %{"key_type" => %{"type_ref" => "primitive/string"}, "peer_id" => %{"type_ref" => "system/peer-id"}, "public_key" => %{"type_ref" => "primitive/bytes"}}}},
      {"system/peer-id", %{"name" => "system/peer-id", "extends" => "primitive/string"}},
      {"system/signature", %{"name" => "system/signature", "fields" => %{"algorithm" => %{"type_ref" => "primitive/string"}, "signature" => %{"type_ref" => "primitive/bytes"}, "signer" => %{"type_ref" => "system/hash"}, "target" => %{"type_ref" => "system/hash"}}}},
      {"system/protocol/connect/authenticate", %{"name" => "system/protocol/connect/authenticate", "fields" => %{"key_type" => %{"type_ref" => "primitive/string"}, "nonce" => %{"type_ref" => "primitive/bytes"}, "peer_id" => %{"type_ref" => "system/peer-id"}, "public_key" => %{"type_ref" => "primitive/bytes"}}}},
      {"system/protocol/connect/hello", %{"name" => "system/protocol/connect/hello", "fields" => %{"compression" => %{"optional" => true, "array_of" => %{"type_ref" => "primitive/string"}}, "encryption" => %{"optional" => true, "array_of" => %{"type_ref" => "primitive/string"}}, "hash_formats" => %{"optional" => true, "array_of" => %{"type_ref" => "primitive/string"}}, "key_types" => %{"optional" => true, "array_of" => %{"type_ref" => "primitive/string"}}, "nonce" => %{"type_ref" => "primitive/bytes"}, "peer_id" => %{"type_ref" => "system/peer-id"}, "protocols" => %{"array_of" => %{"type_ref" => "primitive/string"}}, "timestamp" => %{"type_ref" => "primitive/uint"}}}},
      {"system/protocol/error", %{"name" => "system/protocol/error", "fields" => %{"code" => %{"type_ref" => "primitive/string"}, "message" => %{"type_ref" => "primitive/string", "optional" => true}, "rejected_marker" => %{"type_ref" => "system/hash", "optional" => true}}}},
      {"system/protocol/execute", %{"name" => "system/protocol/execute", "fields" => %{"author" => %{"type_ref" => "system/hash", "optional" => true}, "bounds" => %{"type_ref" => "system/bounds", "optional" => true}, "capability" => %{"type_ref" => "system/hash", "optional" => true}, "deliver_to" => %{"type_ref" => "system/delivery-spec", "optional" => true}, "deliver_token" => %{"type_ref" => "system/hash", "optional" => true}, "durability_request" => %{"type_ref" => "system/durability-request", "optional" => true}, "operation" => %{"type_ref" => "primitive/string"}, "params" => %{"type_ref" => "core/entity"}, "request_id" => %{"type_ref" => "primitive/string"}, "resource" => %{"type_ref" => "system/protocol/resource-target", "optional" => true}, "uri" => %{"type_ref" => "system/tree/path"}}}},
      {"system/protocol/execute/response", %{"name" => "system/protocol/execute/response", "fields" => %{"durability" => %{"type_ref" => "system/durability-result", "optional" => true}, "request_id" => %{"type_ref" => "primitive/string"}, "result" => %{"type_ref" => "core/entity"}, "status" => %{"type_ref" => "primitive/uint"}}}},
      {"system/protocol/resource-target", %{"name" => "system/protocol/resource-target", "fields" => %{"exclude" => %{"optional" => true, "array_of" => %{"type_ref" => "system/tree/path"}}, "targets" => %{"array_of" => %{"type_ref" => "system/tree/path"}}}}},
      {"system/capability/grant", %{"name" => "system/capability/grant", "fields" => %{"token" => %{"type_ref" => "system/hash"}}}},
      {"system/capability/grant-entry", %{"name" => "system/capability/grant-entry", "fields" => %{"allowances" => %{"optional" => true, "map_of" => %{"type_ref" => "primitive/any"}}, "constraints" => %{"optional" => true, "map_of" => %{"type_ref" => "primitive/any"}}, "handlers" => %{"type_ref" => "system/capability/path-scope"}, "operations" => %{"type_ref" => "system/capability/id-scope"}, "peers" => %{"type_ref" => "system/capability/id-scope", "optional" => true}, "resources" => %{"type_ref" => "system/capability/path-scope"}}}},
      {"system/capability/id-scope", %{"name" => "system/capability/id-scope", "fields" => %{"exclude" => %{"optional" => true, "array_of" => %{"type_ref" => "primitive/string"}}, "include" => %{"array_of" => %{"type_ref" => "primitive/string"}}}}},
      {"system/capability/path-scope", %{"name" => "system/capability/path-scope", "fields" => %{"exclude" => %{"optional" => true, "array_of" => %{"type_ref" => "system/tree/path"}}, "include" => %{"array_of" => %{"type_ref" => "system/tree/path"}}}}},
      {"system/capability/request", %{"name" => "system/capability/request", "fields" => %{"grants" => %{"array_of" => %{"type_ref" => "system/capability/grant-entry"}}, "ttl_ms" => %{"type_ref" => "primitive/uint", "optional" => true}}}},
      {"system/capability/revocation", %{"name" => "system/capability/revocation", "fields" => %{"reason" => %{"type_ref" => "primitive/string", "optional" => true}, "revoked_at" => %{"type_ref" => "primitive/uint"}, "token" => %{"type_ref" => "system/hash"}}}},
      {"system/capability/revoke-request", %{"name" => "system/capability/revoke-request", "fields" => %{"reason" => %{"type_ref" => "primitive/string", "optional" => true}, "token" => %{"type_ref" => "system/hash"}}}},
      {"system/capability/delegate-request", %{"name" => "system/capability/delegate-request", "fields" => %{"grants" => %{"array_of" => %{"type_ref" => "system/capability/grant-entry"}}, "parent" => %{"type_ref" => "system/hash"}, "ttl_ms" => %{"type_ref" => "primitive/uint", "optional" => true}}}},
      {"system/capability/delegation-caveats", %{"name" => "system/capability/delegation-caveats", "fields" => %{"max_delegation_depth" => %{"type_ref" => "primitive/uint", "optional" => true}, "max_delegation_ttl" => %{"type_ref" => "primitive/uint", "optional" => true}, "no_delegation" => %{"type_ref" => "primitive/bool", "optional" => true}}}},
      {"system/capability/policy-entry", %{"name" => "system/capability/policy-entry", "fields" => %{"grants" => %{"array_of" => %{"type_ref" => "system/capability/grant-entry"}}, "notes" => %{"type_ref" => "primitive/string", "optional" => true}, "peer_pattern" => %{"type_ref" => "primitive/string"}, "ttl_ms" => %{"type_ref" => "primitive/uint", "optional" => true}}}},
      {"system/capability/token", %{"name" => "system/capability/token", "fields" => %{"created_at" => %{"type_ref" => "primitive/uint"}, "delegation_caveats" => %{"type_ref" => "system/capability/delegation-caveats", "optional" => true}, "expires_at" => %{"type_ref" => "primitive/uint", "optional" => true}, "grantee" => %{"type_ref" => "system/hash"}, "granter" => %{"union_of" => [%{"type_ref" => "system/hash"}, %{"type_ref" => "system/capability/multi-granter"}]}, "grants" => %{"array_of" => %{"type_ref" => "system/capability/grant-entry"}}, "not_before" => %{"type_ref" => "primitive/uint", "optional" => true}, "parent" => %{"type_ref" => "system/hash", "optional" => true}, "resource_limits" => %{"type_ref" => "system/resource-limits", "optional" => true}}}},
      {"system/capability/multi-granter", %{"name" => "system/capability/multi-granter", "fields" => %{"signers" => %{"array_of" => %{"type_ref" => "system/hash"}}, "threshold" => %{"type_ref" => "primitive/uint"}}}},
      {"system/handler", %{"name" => "system/handler", "fields" => %{"expression_path" => %{"type_ref" => "system/tree/path", "optional" => true}, "interface" => %{"type_ref" => "system/tree/path"}, "internal_scope" => %{"optional" => true, "array_of" => %{"type_ref" => "system/capability/grant-entry"}}, "max_scope" => %{"optional" => true, "array_of" => %{"type_ref" => "system/capability/grant-entry"}}}}},
      {"system/handler/interface", %{"name" => "system/handler/interface", "fields" => %{"name" => %{"type_ref" => "primitive/string"}, "operations" => %{"map_of" => %{"type_ref" => "system/handler/operation-spec"}}, "pattern" => %{"type_ref" => "system/tree/path"}}}},
      {"system/handler/manifest", %{"name" => "system/handler/manifest", "fields" => %{"expression_path" => %{"type_ref" => "system/tree/path", "optional" => true}, "internal_scope" => %{"optional" => true, "array_of" => %{"type_ref" => "system/capability/grant-entry"}}, "max_scope" => %{"optional" => true, "array_of" => %{"type_ref" => "system/capability/grant-entry"}}, "name" => %{"type_ref" => "primitive/string"}, "operations" => %{"map_of" => %{"type_ref" => "system/handler/operation-spec"}}, "pattern" => %{"type_ref" => "system/tree/path"}}, "extends" => "system/handler/interface"}},
      {"system/handler/operation-spec", %{"name" => "system/handler/operation-spec", "fields" => %{"input_type" => %{"type_ref" => "system/type/name", "optional" => true}, "output_type" => %{"type_ref" => "system/type/name", "optional" => true}}}},
      {"system/handler/register-request", %{"name" => "system/handler/register-request", "fields" => %{"manifest" => %{"type_ref" => "system/handler/manifest"}, "requested_scope" => %{"optional" => true, "array_of" => %{"type_ref" => "system/capability/grant-entry"}}, "types" => %{"optional" => true, "map_of" => %{"type_ref" => "system/type"}}}}},
      {"system/handler/register-result", %{"name" => "system/handler/register-result", "fields" => %{"grant" => %{"type_ref" => "system/capability/token"}, "pattern" => %{"type_ref" => "system/tree/path"}}}},
      {"system/tree/get-request", %{"name" => "system/tree/get-request", "fields" => %{"limit" => %{"type_ref" => "primitive/uint", "optional" => true}, "mode" => %{"type_ref" => "primitive/string", "optional" => true}, "offset" => %{"type_ref" => "primitive/uint", "optional" => true}, "tree_id" => %{"type_ref" => "primitive/string", "optional" => true}}}},
      {"system/tree/put-request", %{"name" => "system/tree/put-request", "fields" => %{"entity" => %{"type_ref" => "core/entity", "optional" => true}, "expected_hash" => %{"type_ref" => "system/hash", "optional" => true}, "tree_id" => %{"type_ref" => "primitive/string", "optional" => true}}}},
      {"system/tree/listing", %{"name" => "system/tree/listing", "fields" => %{"count" => %{"type_ref" => "primitive/uint"}, "entries" => %{"map_of" => %{"type_ref" => "system/tree/listing-entry"}}, "next_page" => %{"type_ref" => "system/hash", "optional" => true}, "offset" => %{"type_ref" => "primitive/uint"}, "path" => %{"type_ref" => "system/tree/path"}}}},
      {"system/tree/listing-entry", %{"name" => "system/tree/listing-entry", "fields" => %{"has_children" => %{"type_ref" => "primitive/bool"}, "hash" => %{"type_ref" => "system/hash", "optional" => true}}}},
      {"system/tree/path", %{"name" => "system/tree/path", "extends" => "primitive/string"}},
      {"system/type", %{"name" => "system/type", "fields" => %{"extends" => %{"type_ref" => "system/type/name", "optional" => true}, "fields" => %{"optional" => true, "map_of" => %{"type_ref" => "system/type/field-spec"}}, "layout" => %{"optional" => true, "array_of" => %{"type_ref" => "primitive/string"}}, "name" => %{"type_ref" => "system/type/name"}, "type_args" => %{"optional" => true, "map_of" => %{"type_ref" => "system/type/name"}}, "type_params" => %{"optional" => true, "array_of" => %{"type_ref" => "primitive/string"}}}}},
      {"system/type/field-spec", %{"name" => "system/type/field-spec", "fields" => %{"array_of" => %{"type_ref" => "system/type/field-spec", "optional" => true}, "byte_size" => %{"type_ref" => "primitive/uint", "optional" => true}, "constraints" => %{"optional" => true, "array_of" => %{"type_ref" => "core/entity"}}, "default" => %{"type_ref" => "primitive/any", "optional" => true}, "key_type" => %{"type_ref" => "system/type/name", "optional" => true}, "map_of" => %{"type_ref" => "system/type/field-spec", "optional" => true}, "optional" => %{"type_ref" => "primitive/bool", "optional" => true}, "type_args" => %{"optional" => true, "map_of" => %{"type_ref" => "system/type/name"}}, "type_param" => %{"type_ref" => "primitive/string", "optional" => true}, "type_ref" => %{"type_ref" => "system/type/name", "optional" => true}, "union_of" => %{"optional" => true, "array_of" => %{"type_ref" => "system/type/field-spec"}}}}},
      {"system/type/name", %{"name" => "system/type/name", "extends" => "primitive/string"}},
      {"system/bounds", %{"name" => "system/bounds", "fields" => %{"budget" => %{"type_ref" => "primitive/uint", "optional" => true}, "cascade_depth" => %{"type_ref" => "primitive/uint", "optional" => true}, "chain_id" => %{"type_ref" => "primitive/string", "optional" => true}, "parent_chain_id" => %{"type_ref" => "primitive/string", "optional" => true}, "ttl" => %{"type_ref" => "primitive/uint", "optional" => true}, "visited" => %{"optional" => true, "array_of" => %{"type_ref" => "system/tree/path"}}}}},
      {"system/resource-limits", %{"name" => "system/resource-limits", "fields" => %{"max_budget" => %{"type_ref" => "primitive/uint", "optional" => true}, "max_ttl" => %{"type_ref" => "primitive/uint", "optional" => true}, "max_visited_length" => %{"type_ref" => "primitive/uint", "optional" => true}}}},
      {"system/delivery-spec", %{"name" => "system/delivery-spec", "fields" => %{"operation" => %{"type_ref" => "primitive/string"}, "uri" => %{"type_ref" => "system/tree/path"}}}},
      {"system/deletion-marker", %{"name" => "system/deletion-marker"}},
    ]
  end
end
