#!/usr/bin/env python3
"""author-extension-host.py — write the H5 `[extension_host]` block into every peer profile.

WHY A SCRIPT AND NOT 44 HAND EDITS. The per-peer FACTS below were traced by hand, one peer at
a time, and that is the irreducible work — H5's `dispatch_read_site` is the field that
distinguishes a live host from a dead map, and no tool can derive it. What a script removes is
the OTHER failure mode: 44 near-identical hand edits, where a transcription slip produces a
block that looks right and names the wrong symbol.

WHAT IS DERIVED vs WHAT IS AUTHORED, because the distinction is the honesty of the block:

  * `entity_native_status`, `entity_native_wire_verdict`, `entity_native_verified_by` —
    DERIVED from the executed probe reports in output/scratch/host-seam-probe/. Never from a
    source read. If the probe has not run, this script refuses rather than writing `unknown`
    from nothing. THIS IS NOT H1: the probe registers a body over the WIRE and asserts it
    evaluates, which is §6.13(a), and H1's own Observation excludes exactly that path.
  * `h1_status`, `h1_verified_by` — from H1_EVIDENCE below: an EXECUTED H1 harness (a
    language-native body installed through the public surface, reached by an EXECUTE from a
    second peer). `unknown` for every peer no such harness has run against.

    WHY THE SPLIT (2026-09-12, routed by entity-system-generator as their K-10). Until then
    `h1_status = "host"` was derived from the wire probe's EVALUATES, so 26 profiles read
    `host` on H1 — 17 of them while declaring no in-process install path at all, `rust`
    among them. That is why the generator's 2026-09-06 rust measurement closed with nothing
    moving: the gate said `rust` was already a host. A field named for the requirement it
    does not measure is worse than no field, because every reader trusts the name.
  * `packaging_unit`, `package_name` — DERIVED from the peer's OWN `[publishing]` block. Not
    from an inventory of package-manager filenames a surveyor wrote down: that survey shape
    reports "absent" rather than "could not look", and it already produced a wrong cohort
    count once (H4, 11 of 46 rows wrong).
  * `dispatch_read_site`, `handler_register_call`, `consumer_register_call` — AUTHORED below
    from a per-peer trace, and each names a file and a symbol so a reader can refute it by
    opening the file.

Idempotent: re-running replaces the block it wrote. Run `--check` to verify coverage.
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PG = os.path.join(ROOT, "protocol-generator")
PROBE = os.path.join(ROOT, "output", "scratch", "host-seam-probe")

# Two markers, and the distinction is load-bearing: FULL means this script owns the whole
# block, MEASURED means a hand-authored block owns the prose and only the wire-measured H1
# fields are injected. Deciding ownership by "does an [extension_host] section exist" is what
# the first cut did, and on the SECOND run the section existed because the first run had made
# it -- so regeneration stripped `dispatch_read_site` from all 44 peers. Ownership has to be
# recorded, not inferred.
FULL = "# >>> extension_host FULL (generated by tools/author-extension-host.py) >>>"
MEAS = "# >>> extension_host MEASURED (generated by tools/author-extension-host.py) >>>"
END = "# <<< extension_host <<<"

# The probe's basis, quoted into every block so a reader knows what the status is anchored to.
PROBE_BASIS = ("tools/host-seam-probe @ 2026-09-09, oracle 78db4a9 / executed set 7aa6f3de…, "
               "H1 v1.0 @ 62e1a1dd…")

# ---------------------------------------------------------------------------
# PER-PEER TRACE. Hand-authored. Each dispatch_read_site names the file and the
# symbol where the peer decides WHICH BODY runs — not the registration entry point.
# ---------------------------------------------------------------------------
# key: (handler_register_call, handler_body_shape, dispatch_read_site)
T = {
 "go": ("none -- wire system/handler:register only; `handlers` is unexported and Peer exports only Identity/Store/LocalPeer",
        "entity-native: a system/handler entity with expression_path -> compute/literal",
        "Peer.dispatch -- p.handlers[stripped] for bootstrap bodies, else entityNativeDispatch via p.store.GetAt; src/peer/peer.go:426 and :317"),
 "rust": ("Peer::register_handler(self: &Arc<Peer>, HandlerSpec, body) -> Result<HandlerHandle, RegisterError> (SDK-OPERATIONS §11.6; Peer::install_handler(Arc<dyn Handler>) for the peer's lifetime) -- binds the core §6.13(a) entities, then the body; 400 invalid_handler_spec / 409 pattern_collision before any write (H3); system/* is installable. Contract report: status/KEYSTONE-PEER-REPORT.json",
        "impl Handler { fn handle(&self, &HandlerContext) -> HandlerResult } (FnHandler for closures); or entity-native expression_path, with Peer::set_expression_evaluator as the H7 fallback",
        "Peer::route -- self.native_handlers.read().get(&stripped) after the §6.6 walk (resolve_handler) and before entity_native_dispatch; src/peer/core.rs:801"),
 "python": (None, None, None),      # block already authored; only the H1 fields are added
 "typescript": (None, None, None),  # ditto
 "java": ("none -- `handlers` is a private final HashMap; the wire register op is the only path",
        "entity-native: expression_path -> compute/literal",
        "Peer.dispatch -- handlers.get(stripped); src/main/java/org/entitycore/protocol/peer/Peer.java:1234"),
 "kotlin": ("none -- `handlers` is a private HashMap; wire register op only",
        "entity-native: expression_path -> compute/literal",
        "Peer.dispatch -- handlers[stripped]; src/main/kotlin/org/entitycore/protocol/peer/Peer.kt:891"),
 "csharp": ("Peer.RegisterHandler(IHandler) EXISTS and is public, but `Peer` is `internal sealed` -- unreachable across the ASSEMBLY boundary, which is the packaging boundary in C#",
        "IHandler in-process (unreachable), or entity-native expression_path",
        "Dispatcher.DispatchAsync -- res.Native from HandlerRegistry, else RunEntityNative; src/EntityCore.Protocol/Dispatch/Dispatcher.cs:194"),
 "cpp": ("none reachable -- Peer::register_handler exists but `private:` opens at include/entity_core/peer.hpp:75, so the Handler typedef itself cannot be named by a caller",
        "entity-native only from outside the class",
        "Peer::dispatch -- lookup_handler(stripped); src/dispatch.cpp:1136"),
 "c": ("none -- lookup_handler/ec_handler_fn are static to the translation unit",
        "entity-native declared but NOT evaluated: register drops expression_path",
        "dispatch_execute -- lookup_handler(p, stripped); src/dispatch.c:2246"),
 "haskell": ("none -- wire register op only",
        "entity-native: expression_path -> compute/literal",
        "dispatch -- resolveHandler then entityNativeDispatch reading expression_path from the store; src/EntityCore/Peer.hs:839-846, :922"),
 "ocaml": ("none -- wire register op only",
        "entity-native: expression_path -> compute/literal",
        "dispatch -- resolve_handler then the entity-native arm reading expression_path; src/peer.ml:766-769, :815"),
 "lean": ("none -- wire register op only",
        "entity-native: expression_path -> compute/literal",
        "dispatch -- resolveHandler then the entity-native arm; src/EntityCore/Peer.lean:824-826, :880"),
 "swift": ("none -- invokeHandler is a switch over six built-ins with `default: 501 unsupported_operation`; there is no container",
        "none -- register accepts an expression_path and does not persist it",
        "Peer.invokeHandler -- switch pattern over the six bootstrap handlers, default 501; Sources/EntityCoreProtocol/Peer.swift:452"),
 "elixir": ("none -- wire register op only",
        "entity-native: expression_path -> compute/literal",
        "entity_native_dispatch -- Store.get_at then text_field(he,\"expression_path\"); lib/entity_core/peer.ex:1090-1097"),
 "ruby": ("none -- wire register op only",
        "entity-native: expression_path -> compute/literal",
        "entity_native_dispatch -- @store.get_at then he.text(\"expression_path\"); lib/entity_core/peer.rb:833"),
 "crystal": ("none -- @handlers is an instance var, wire register op only",
        "entity-native: expression_path -> compute/literal",
        "dispatch -- @handlers[stripped]? then entity_native_dispatch(pattern); src/entity_core/peer.cr:365-369"),
 "dart": ("none -- _handlers is private by the leading underscore",
        "entity-native: expression_path -> compute/literal",
        "dispatch -- _handlers[stripped] then _entityNativeDispatch; lib/src/peer/peer.dart:949, :865"),
 "php": ("none -- wire register op only",
        "entity-native: expression_path -> compute/literal",
        "entityNativeDispatch -- store->getAt then he->text('expression_path'); src/Peer.php:304"),
 "python-note": (None, None, None),
 "julia": ("register_handler!(p, pattern, h; operations, name) -- EXPORTED from module Peer and the map IS read (fixed 2026-09-08)",
        "Function (ctx::HandlerContext), or entity-native expression_path",
        "_dispatch -- get(p.handlers, stripped, nothing), consulted AFTER the built-ins so the H7 floor wins; src/peer.jl:856 (ordering asserted in the source at :843-850)"),
 "io": ("Peer _install(pattern, proto, name, ops) -- writes runtimeHandlers; underscore-prefixed by convention, Io enforces no visibility",
        "a Handler clone with dispatch(operation, ctx), or entity-native",
        "dispatch -- runtimeHandlers at(pattern), with EntityNativeHandler for stored expressions; src/Peer.io:330"),
 "common-lisp": ("none -- (peer-handlers peer) is a struct slot, wire register op only",
        "a CLOS handler instance, or entity-native expression_path",
        "handler-instance -- (gethash stripped (peer-handlers peer)), else entity-native-dispatch; src/peer.lisp:~860, :847"),
 "zig": ("none -- registerHandler is the WIRE op (takes an Entity exec) and is not `pub`",
        "entity-native: expression_path -> compute/literal",
        "entityNativeDispatch -- handler_entity.textField(\"expression_path\"); src/peer.zig:936"),
 "odin": ("none -- wire register op only",
        "entity-native: expression_path -> compute/literal",
        "entity_native_dispatch -- entity_text(handler_entity,\"expression_path\"); src/peer.odin:1159"),
 "nim": ("none -- wire register op only",
        "none evaluated -- register PERSISTS expression_path and dispatch never reads it",
        "dispatchOutcome -- `case pattern` over the six built-ins, `else: 501 no_handler_body`; src/peer.nim:873"),
 "ada": ("none -- Dispatch is an if/elsif ladder over Stripped with no container",
        "none -- register accepts an expression_path and does not persist it",
        "Dispatch_Request -- elsif ladder on Stripped, else 501 no_handler_body; src/entity_core-protocol-handlers.adb:1651"),
 "tcl": ("none -- wire register op only",
        "entity-native: expression_path -> compute/literal",
        "::entity::core::peer::_entity_native_dispatch -- entity text $he expression_path; src/peer.tcl:237"),
 "rexx": ("none -- wire register op only",
        "entity-native: expression_path -> compute/literal",
        "_entity_native_dispatch -- Ent_Text(he,'expression_path'); src/peer.rex:316"),
 "smalltalk": ("EcPeer>>registerHandler:as: writes the in-image `handlers` Dictionary (Smalltalk has no access control, so it is reachable); the WIRE register op does not touch that map -- it binds a system/handler entity into the TREE, which resolution now reads (F62)",
        "a block [:ctx | ...] in-process; an entity-native body is bound and not evaluated -> 501 no_handler_body",
        "EcPeer>>resolveHandler: -- the §6.6 backward walk, hitting on `handlers includesKey: p` OR a system/handler entity at `store getAt: (self peerAbs: p)`; the body then comes from the map in runHandler:, and a resolved path with no block is 501, not 404; src/EntityCore-Peer/EcPeer.st:102, :222"),
 "oz": ("none -- wire register op only",
        "none evaluated -- bound, then the stripped-pattern match falls through",
        "Dispatch -- match on Stripped, else {OutErr 501 \"no_handler_body\" Stripped}; src/peer.oz:295"),
 "prolog": ("none -- wire register op only",
        "none -- register accepts an expression_path and does not persist it",
        "authorized_dispatch/5 -- resolve_handler(Peer,Path,Pattern) then a clause head per built-in; prolog/ec_peer.pl:249, :537"),
 "sql": ("none -- register_handler_entities is a static C helper in the host shim",
        "none -- register accepts an expression_path and does not persist it",
        "dispatch_execute -- strcmp ladder over `rel`, falling to 501 no_handler_body; src/host/handlers.inc.c:711"),
 "datalog": ("none -- wire register op only",
        "none evaluated -- expression_path is copied at register time only (src/dispatch.rs:1478)",
        "dispatch -- match on stripped, `_ => err_out(501,\"no_handler_body\")`; src/dispatch.rs:593"),
 "unison": ("none -- wire register op only",
        "none -- register accepts an expression_path and does not persist it",
        "routeHandler -- match stripped over the six built-ins, `_ -> 501 no_handler_body`; src/Peer.u:865-871"),
 "apl": ("none -- CallHandler dispatches on a numeric routine id, no container",
        "none -- register accepts an expression_path and does not persist it",
        "CallHandler -- branch on the routine id set by resolution, else 501; src/peer.apl:280-296"),
 "cobol": ("none in-process -- the WIRE register op binds a system/handler entity into the TREE, which the §6.6 walk already read; only the BODY-selection miss below was mis-spelled (F62)",
        "entity-native declared; a resolved pattern with no COBOL handler is 501 no_handler_body",
        "`resolve-handler` -- the §6.6 backward walk over store-get-at, type == system/handler; src/capability.cob:1179. The `when splen = N` ladder below it is BODY SELECTION, not resolution: its `when other` is 501 (src/peer.cob:388), because hfound=0 already took the 404"),
 "fortran": ("none in-process -- reg_handler fills the routine table at bootstrap; the WIRE register op binds a system/handler entity into the TREE, which the §6.6 walk already read (F62)",
        "entity-native declared; a resolved pattern with no routine is 501 no_handler_body",
        "`resolve_handler` -- the §6.6 backward walk over store_get_at, ent_type == system/handler; src/peer.f90:303. `handler_routine(stripped) == 0` below it is BODY SELECTION -> 501 (src/peer.f90:439); the len(pattern)==0 arm is the 404"),
 "forth": ("none in-process -- hnd-lookup is the native-word table; the WIRE register op binds a system/handler entity into the TREE, which the §6.6 walk now reads at the CANONICAL path (F62)",
        "entity-native declared; a resolved pattern with no native word is 501 no_handler_body",
        "`resolve-handler` -- the §6.6 backward walk, probing `paddr plen peer-abs store-get-at` (the peer-rooted absolute key every write uses); src/handlers.fs:243. `hnd-lookup` in dispatch is BODY SELECTION, below the authz gate -> 501; src/dispatch.fs:149"),
 "asm-x86_64": ("none in-process -- the op ladder is compile-time; the WIRE register op binds a system/handler entity into the per-fork store, which the §6.6 walk now reads (F62)",
        "entity-native declared; a resolved pattern with no native body is 501 no_handler_body",
        "`uri_handler_in_tree` -- the §6.6 backward walk over store_handler_at (canon_path + store_get + type == system/handler); src/dispatch.s:5793. Consulted AFTER `uri_handler_known` (the native index) at the 404 site, so an empty store behaves as before; the walk-only arm is 501 at :689"),
 "asm-arm64": ("none in-process -- as asm-x86_64 (same authored lineage, ported)",
        "entity-native declared; a resolved pattern with no native body is 501 no_handler_body",
        "`uri_handler_in_tree` -- the §6.6 backward walk over store_handler_at; src/dispatch.s:5659, 501 arm at :671 (ported from asm-x86_64)"),
 "riscv64": ("none in-process -- as asm-x86_64 (same authored lineage, ported)",
        "entity-native declared; a resolved pattern with no native body is 501 no_handler_body",
        "`uri_handler_in_tree` -- the §6.6 backward walk over store_handler_at; src/dispatch.s:6039, 501 arm at :689 (ported from asm-x86_64)"),
 "wasm-wat": ("none -- $derive_handler sets a global handler pointer; no container",
        "none -- register accepts an expression_path and does not persist it",
        "dispatch.wat -- $derive_handler at :2949, $g_hptr :1175; unresolved -> handler_not_found"),
 "pd": ("none -- the dispatch spine is on the canvas",
        "none -- register accepts an expression_path and does not persist it",
        "main.pd -- the §6.6 longest-prefix walk (walk_prefix/tree_get/type==system/handler), then dispatch; src/main.pd:71, :85"),
 "node-red": ("inherits `typescript` -- this peer is a Node-RED node wrapping that engine",
        "inherits typescript",
        "inherits typescript's HandlerRegistry.resolve; the seam here is src/lib/session.js"),
 "turbowarp": ("inherits the typescript engine, bundled for the browser",
        "inherits typescript",
        "inherits typescript's dispatcher via the bundled engine; src/dist/ec-core-browser.js"),
 "rust-wasm": ("inherits `rust` (path dependency ../rust) -- rust has no in-process API",
        "inherits rust: entity-native only",
        "inherits rust's Peer::dispatch; this peer is a transport seam only"),
 "rust-wasm-wasmtime": ("inherits `rust` (path dependency ../rust) -- rust has no in-process API",
        "inherits rust: entity-native only",
        "inherits rust's Peer::dispatch; this peer is a transport seam only"),
}

CONSUMER = {
 "c": "ec_store_register_tree_consumer", "cpp": "Store::register_tree_consumer",
 "crystal": "Store#register_tree_consumer / register_content_consumer",
 "csharp": "EmitBus.RegisterConsumer (public member of an internal type -- see status)",
 "elixir": "Store.register_tree_consumer/1 / register_content_consumer/1",
 "ocaml": "Store.register_tree_consumer / register_content_consumer",
 "prolog": "register_tree_consumer/1 / register_content_consumer/1",
 "ruby": "Store#register_tree_consumer / register_content_consumer",
 "rust": "Store::register_tree_consumer -- MEASURED live by the generator's rust arm (emit face: YES)",
 "tcl": "::entity::core::store::register_tree_consumer / register_content_consumer",
 "node-red": "inherits typescript's EmitBus.registerConsumer",
 "turbowarp": "inherits typescript's EmitBus.registerConsumer",
}

HANDLE_LIFECYCLE = {
 "rust": "HandlerHandle::close() -> bool (idempotent; Drop closes; detach() keeps) -- dispatch index first, then handler/interface/grant; types stay. Peer::unregister_handler(pattern) removes any native body",
}

FRAME_BUDGET = {"python": "DispatchCtx.frame_budget()", "typescript": "HandlerContext.frameBudget()",
                "rust": "HandlerContext::frame_budget() -- the connection's value, peer default as fallback; configured with PeerConfig::max_frame_bytes",
                "turbowarp": "inherits typescript's HandlerContext.frameBudget()"}

# The wire probe's verdict → the entity-native (§6.13(a)) status. Deliberately NOT spelled
# `host`: that word is H1's, and reusing it here is the K-10 defect.
STATUS_OF = {
    "EVALUATES": "evaluates",
    "EVALUATES-UNVERIFIED": "evaluates",
    "BOUND-NOT-EVALUATED": "not-yet",
    "REGISTER-DROPPED-EXPRESSION-PATH": "not-yet",
    "NOT-RESOLVED": "not-yet",
    "CONTROL-FAILED": "unknown",
    "UNTRUSTED": "unknown",
}


# H1 — EXECUTED evidence only. A peer absent from this table reads `unknown`, never a
# status inferred from the wire probe or from a source trace.
H1_UNKNOWN = ("unknown",
              "no executed H1 harness for this peer. The entity_native_* fields are the "
              "§6.13(a) wire measurement, which H1's Observation excludes")
H1_EVIDENCE = {
 "rust": ("host",
          "protocol-generator/rust/tests/host_contract.rs h1_installed_body_is_reached_from_a_second_peer "
          "(keystone, executed 2026-09-12: Peer::register_handler, EXECUTE from a second peer over "
          "loopback, witness = request field + registration nonce; planting the read site reddens it)"),
 "typescript": ("host",
          "protocol-generator/shared/diagnostics/host-seam-probe-typescript.mjs + "
          "protocol-generator/typescript/test/host-seam.test.ts (keystone, executed)"),
 "python": ("not-yet",
          "entity-system-generator gates/host-seam/probe-seam.py reaches a body through the public "
          "`handlers` dict (executed), but the peer has no registration call, and H3: exposing the "
          "raw container does not satisfy H1"),
}


def tstr(s):
    """Emit a TOML basic string, escaped.

    Not decoration: the trace values below quote real source (`he.text("expression_path")`),
    and interpolating them raw produced seven profiles that do not parse. The postcondition
    check caught it; this is the fix. Escape order matters — backslash first.
    """
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def kv(key, value):
    return f"{key:<23} = {tstr(value)}"


def publishing(text):
    m = re.search(r"^\[publishing\](.*?)(?=^\[)", text, re.S | re.M)
    if not m:
        return None, None
    blk = m.group(1)
    reg = re.search(r'^registry\s*=\s*"([^"]*)"', blk, re.M)
    pid = re.search(r'^package_id\s*=\s*"([^"]*)"', blk, re.M)
    return (reg.group(1) if reg else None), (pid.group(1) if pid else None)


def build_block(peer, verdict, prof_text, have_section):
    """Return the delimited fragment.

    `have_section` decides whether the fragment carries its own `[extension_host]`
    header. It matters: appending bare `key = value` lines to a profile puts them in
    whatever table the file ENDS in — every profile here ends in `[spec]` — which is
    valid TOML and silently wrong. Caught by parsing the result, not by reading it.

    Where a hand-authored block already exists (`python`, `typescript`) only the
    measured fields are injected, immediately under the section header, and the
    hand-authored prose and fields are left untouched.
    """
    reg, pid = publishing(prof_text)
    trace = T.get(peer)
    h1 = H1_EVIDENCE.get(peer, H1_UNKNOWN)
    lines = []
    if not have_section:
        lines.append("[extension_host]")
    lines += [MEAS if have_section else FULL,
             "# H5 -- the keystone host contract's platform bindings. See",
             "# docs/spec/SPEC-KEYSTONE-PEER.md (H1..H9 @ 62e1a1dd...).",
             "#",
             "# TWO MEASUREMENTS, and until 2026-09-12 they shared one name. `h1_status` is H1:",
             "# a LANGUAGE-NATIVE body installed through the public surface and reached by an",
             "# EXECUTE from a second peer. It reads `unknown` until such a harness has executed,",
             "# and `h1_verified_by` names it. `entity_native_*` is tools/host-seam-probe: a body",
             "# registered over the WIRE is dispatched and evaluated -- §6.13(a), which H1's own",
             "# Observation excludes. `dispatch_read_site` is the load-bearing descriptive field.",
             kv("h1_status", h1[0]),
             kv("h1_verified_by", h1[1]),
             kv("entity_native_status", STATUS_OF.get(verdict, "unknown")),
             kv("entity_native_wire_verdict", verdict),
             kv("entity_native_verified_by", PROBE_BASIS)]
    if not have_section:
        # Only author the descriptive fields where no hand-authored block already
        # states them. Overwriting a hand-written `dispatch_read_site` with a
        # generated one would replace a traced fact with a table entry.
        if trace and trace[0]:
            lines += [kv("status", h1[0]),
                      kv("handler_register_call", trace[0]),
                      kv("handler_body_shape", trace[1]),
                      kv("dispatch_read_site", trace[2])]
        lines.append(kv("consumer_register_call",
                        CONSUMER.get(peer, "none -- no in-process emit-consumer registration surface")))
        lines.append(kv("frame_budget_accessor", FRAME_BUDGET.get(peer, "absent")))
        lines.append(kv("handle_lifecycle", HANDLE_LIFECYCLE.get(peer, "absent -- unregister is the wire op")))
        lines.append(kv("packaging_unit", reg or "undeclared -- no [publishing] block"))
        lines.append(kv("package_name", pid or "undeclared"))
    lines.append(END)
    return "\n".join(lines) + "\n"


def validate(peers):
    """The properties the block exists for, asserted on the COMMITTED profiles.

    Run in BOTH modes. The first cut ran these only after a write, so `--check` never
    reached them: a planted `h1_status = "host"` resting on the wire probe was reported as
    merely STALE, and on a clean clone -- where the gitignored probe reports do not exist
    -- it was not reported at all. A discriminator that only runs on the writer's machine
    is not an enforcement point.
    """
    import tomllib
    bad = []
    for p in peers:
        with open(os.path.join(PG, p, "profile.toml"), "rb") as fh:
            try:
                d = tomllib.load(fh)
            except Exception as e:
                bad.append(f"{p}: does not parse: {e}")
                continue
        eh = d.get("extension_host")
        if not isinstance(eh, dict):
            bad.append(f"{p}: no [extension_host] table")
        elif "h1_status" not in eh or "entity_native_wire_verdict" not in eh:
            bad.append(f"{p}: [extension_host] missing the H1 or entity-native fields")
        elif "h1_wire_verdict" in eh:
            bad.append(f"{p}: [extension_host] still carries h1_wire_verdict (renamed entity_native_wire_verdict, K-10)")
        elif eh["h1_status"] not in ("host", "not-yet", "declined", "unknown"):
            bad.append(f"{p}: h1_status {eh['h1_status']!r} is not host | not-yet | declined | unknown")
        elif eh["h1_status"] != "unknown" and "host-seam-probe @" in eh.get("h1_verified_by", ""):
            # The K-10 discriminator, asserted: an H1 claim may not rest on the wire probe,
            # because the probe measures the entity-native fallback H1 excludes.
            bad.append(f"{p}: h1_status {eh['h1_status']!r} rests on tools/host-seam-probe, which is not an H1 harness")
        elif "dispatch_read_site" not in eh:
            # The load-bearing field. Checking only the H1 keys is how a regeneration
            # that STRIPPED dispatch_read_site from 44 peers reported "0 problems" --
            # a check must assert the proposition the artifact exists for.
            bad.append(f"{p}: [extension_host] has no dispatch_read_site")
        elif "spec" in d and "h1_status" in d.get("spec", {}):
            bad.append(f"{p}: H1 fields leaked into [spec]")
    return bad


def main():
    check = "--check" in sys.argv
    verdicts = {}
    for fn in os.listdir(PROBE) if os.path.isdir(PROBE) else []:
        if fn.endswith(".json"):
            d = json.load(open(os.path.join(PROBE, fn)))
            if "verdict" in d:
                verdicts[d["peer"]] = d["verdict"]
    peers = sorted(p for p in os.listdir(PG)
                   if os.path.isfile(os.path.join(PG, p, "profile.toml")))
    missing = [p for p in peers if p not in verdicts]
    if missing and check:
        # Staleness needs the probe reports; the properties do not. Say which was skipped.
        print(f"author-extension-host --check: no probe reports for {len(missing)} peer(s) -- "
              f"staleness NOT compared for them; properties still validated")
    elif missing:
        sys.exit(f"author-extension-host: no executed probe report for {missing}. "
                 f"Run tools/run-cohort-census.sh --probe host-seam-probe first — this script "
                 f"will not write a status it has not measured.")
    wrote = skipped = 0
    problems = []
    for p in peers:
        path = os.path.join(PG, p, "profile.toml")
        text = open(path).read()
        # Ownership is READ FROM THE MARKER, never inferred from the section existing.
        if FULL in text:
            have_section = False          # ours entirely; regenerate every field
        elif MEAS in text:
            have_section = True           # hand-authored prose; only the H1 fields are ours
        else:
            have_section = re.search(r"^\[extension_host\]", text, re.M) is not None
        if p not in verdicts:
            skipped += 1
            continue
        block = build_block(p, verdicts[p], text, have_section)
        marker = MEAS if have_section else FULL
        if marker in text:
            pat = re.escape(marker) + r".*?" + re.escape(END) + r"\n"
            if not have_section:
                # our FULL block owns its own [extension_host] header too
                pat = r"\[extension_host\]\n" + pat
            new = re.sub(pat, lambda _m: block, text, flags=re.S)
        elif have_section:
            new = re.sub(r"^(\[extension_host\]\n)", lambda m: m.group(1) + block,
                         text, count=1, flags=re.M)
        else:
            new = text.rstrip("\n") + "\n\n" + block
        if check:
            if FULL not in text and MEAS not in text:
                problems.append(f"{p}: no generated [extension_host] block")
            elif new != text:
                problems.append(f"{p}: block is STALE (re-run tools/author-extension-host.py)")
            skipped += 1
            continue
        if new != text:
            open(path, "w").write(new)
            wrote += 1
        else:
            skipped += 1
    if check:
        problems += validate(peers)
        for m in problems:
            print("  " + m)
        # Print the COUNT, always: a gate that examined zero things prints the same
        # word as one that examined forty-six.
        print(f"author-extension-host --check: {len(peers)} peer(s) examined, {len(problems)} problem(s)")
        sys.exit(1 if problems else 0)
    # POSTCONDITION, not the edit. Verifying "the file changed" says nothing; the first
    # cut of this script emitted the fields with NO `[extension_host]` header, so they
    # landed in whatever table each profile ends in (`[spec]`, in all 46). That is valid
    # TOML and completely wrong, and only parsing the result says so.
    bad = validate(peers)
    for m in bad:
        print("  " + m)
    print(f"author-extension-host: {len(peers)} peer(s) examined, {wrote} written, "
          f"{skipped} unchanged, {len(bad)} postcondition failure(s)")
    if bad:
        sys.exit(1)


if __name__ == "__main__":
    main()
