#!/usr/bin/env python3
"""coherence-gate — a published number must equal the report it is published from.

WHY THIS EXISTS. `make lint` already runs three gates and the release pipeline runs six,
and between the nine of them **not one asks whether a document agrees with itself.**
`check-set-gate` asks whether numbers are COMPARABLE, `pin-gate` whether anchors RESOLVE,
`link-gate` whether links point at real FILES. All nine pass a tree in which
`CONFORMANCE-MATRIX.md` §1 publishes `595P/54W` for a peer whose own committed report says
`313P/336W`.

That is not hypothetical and it is not rare. Every documentation defect found in the two
weeks before this gate was written was found by *walking the tree by hand*, with `make lint`
green throughout: a footnote describing a peer at 3F attached to a row reading 0F; a footnote
asserting three quarantined peers six lines above "45 of 45 conforming"; four closed backlog
items still marked open, two of them High; a §4 table a week stale; and two published
cross-references to a `§5` that does not exist in that file.

WHAT IT CHECKS

  1. **§1 primary-status-table rows (GATING).** Every row carries `NNNP/NNW/NF/NNNS` and a
     `755 · NF` headline. Both must equal that peer's committed
     `status/CONFORMANCE-REPORT.json`. This is the highest-consequence number in the repo:
     it is what an adopter reads, and [ADR-0012] makes it the credibility artifact.

  2. **Each peer's own prose banner (GATING).** `status/CONFORMANCE-REPORT.md` is what a
     reader opens before the JSON. It is generated by `status-banner.py`, but nothing
     re-checked it after generation, and a hand-edit leaves no trace.

  3. **Row-name resolution (GATING, fail-closed).** A §1 row whose bolded name does not
     resolve to a peer directory is an ERROR, not a skip. A gate that silently ignores rows
     it cannot parse is the `Path.stem` collision again — it "passes" having examined
     nothing. All 46 rows must resolve or this exits non-zero.

  4. **Stale P/W/F/S anywhere in live prose (REPORTED, not gating).** Any `NNNP/NNW/NF/NNNS`
     in a tracked `.md` that matches NO committed report is surfaced. It cannot be gating:
     this repo deliberately quotes superseded figures as evidence — footnote ⁷ keeps a peer's
     whole FAIL-count progression precisely because the sequence is the finding, and
     `AGENTS.md` quotes a past README defect verbatim. Those are correct and must not be
     "fixed". Severity is split for the same reason `link-gate` splits it: a gate held
     permanently red by legitimate content teaches people to skip it.

  5. **Dangling self-references (GATING, narrow).** A bare `§X` reference whose base number
     is a top-level section this file DEFINES, but where `X` itself is not defined —
     e.g. `§1e` in a file with `§1a`–`§1d`, or `§2a` where §2 has no lettered parts.

  6. **A RETIRED PIN PRESENTED AS THE CURRENT ONE (GATING).** Checks 1–3 gate §1's rows and the
     46 per-peer banners; nothing gated the sentences that tell a reader WHICH PIN those rows
     were measured at. Measured 2026-09-09, with all thirteen gates green: **five live sites in
     four published files** named a retired executed-check-set digest in the present tense —
     `README.md` twice (the front door, two flips stale), `docs/STATUS.md`, `docs/PROGRAM.md`,
     and `CONFORMANCE-MATRIX.md`'s own footnotes ² and ⁶, one of which defines what every cell
     in §1 means and was **three** flips behind. §1 was correct throughout, which is exactly why
     nothing caught it.
     The rule: in a live PARAGRAPH carrying a **pin phrase** (`the pin`, `Oracle pin`,
     `pinned as/set/snapshot`, `pinned NNN-check`, `NNN-check pin`, `fresh measurement at`,
     `required to execute`, `at one pin`), every check-set digest and every `NNN-check` total
     must be the CURRENT one from `tools/oracle-pin.env`.
     **Four escape hatches, because naming a retired pin in live prose is legitimate and must
     stay cheap:** put a DATE within 80 characters of it; introduce it with `retired` /
     `superseded` / `then-current` / `first closed`; put it inside a `"quotation"` of former
     text; or strike the line (`~~`) / mark it `✅`. Dated `>` blocks are skipped as everywhere
     else in this gate. **The count of pin statements examined is printed and asserted
     non-zero**, because a phrase list that matches nothing reports the same word as one that
     matches everything — this check went 95 → 114 statements when it moved from lines to
     paragraphs, and the 19 it gained included two real defects.

DEFERENCE: dated `>` note blocks are skipped everywhere. They are a build log, and this repo
holds that a build log which gets back-edited stops being evidence of anything.

WHAT THIS DOES NOT CATCH — and the limit is the point, not an apology.

  * **The `§5` defect that motivated check 5 would NOT be caught by it.** `CONFORMANCE-MATRIX.md`
    defines §1–§4 and cited a `§5` of itself; but `§5`, `§6`, `§7a` and `§7b` are also how this
    file cites the *protocol spec*, 24 times, correctly. There is no textual discriminator
    between "§5 of this file" and "§5 of the spec" — and resolving it against the pinned spec
    does not help, because the spec HAS a §5. Check 5 therefore only catches a dangling ref
    inside a section family the file already owns. Widening it produces 24 false positives on
    the matrix alone, which is the signal-to-noise failure that hid a real answer inside its
    own output once already.
  * A number that is internally consistent and simply wrong.
  * Prose that contradicts prose without either quoting a number.

So this is a floor, not the coverage story. **The hand-walk of the published tree stays
mandatory** (`AGENTS.md`, "no gate asks whether the published tree is internally coherent").
A gate that made anyone feel the walk was covered would be worse than no gate.

Exit 0 clean, 1 on any gating failure.  `--self-test` runs the regression suite.
"""

import json
import pathlib
import re
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
MATRIX = "CONFORMANCE-MATRIX.md"

PWFS = re.compile(r"(\d{3})P/(\d{2,3})W/(\d+)F/(\d{3})S")
# The per-peer banner spells the same figures out longhand rather than as P/W/F/S —
# `**755 total · 312 pass · 337 warn · 0 FAIL · 106 skip**`. Matching only the compact form
# made check 2 examine ZERO of the 46 banners while reporting success, which is the exact
# shape this file's docstring warns about; it was caught by printing the count, not by
# reading the code. Always print how many things a check actually looked at.
BANNER = re.compile(
    r"(\d+)\s*total\s*·\s*(\d+)\s*pass\s*·\s*(\d+)\s*warn\s*·\s*(\d+)\s*FAIL\s*·\s*(\d+)\s*skip"
)
# `oracle entity-core-go @ <sha>` — a commit anchor in a file that publishes.
ORACLE_COMMIT = re.compile(r"entity-core-go\s*@\s*[0-9a-f]{7,40}")
# A §1 row: bolded display name in the first cell, a P/W/F/S somewhere in it. The cell may
# carry a trailing qualifier after the bold — `**Go** (clean-room)`, `**Node-RED**‡` — so the
# tail up to the next pipe is consumed and discarded rather than required to be empty.
ROW = re.compile(r"^\|\s*\*\*([^*]+)\*\*[^|]*\|")
# `755 · 0F` headline inside a row. The count may itself be bolded (`755 · **0F**`).
HEADLINE = re.compile(r"(\d{3})\s*·\s*\**(\d+)F")
# Bare section ref: §N or §Na, NOT followed by a digit, '.' or '('.
SECREF = re.compile(r"§(\d+)([a-z])?(?![0-9.(])")
# `## 1a. ...` / `## 3. ...`
HEADING = re.compile(r"^#{1,6}\s+(\d+)([a-z])?\.\s", re.M)


# Display names in §1 that do not normalize to their directory.
ALIASES = {
    "c#": "csharp",
    "c++": "cpp",
    "oz / mozart": "oz",
    "pure data": "pd",
}


def peer_dir(display):
    key = display.strip().lower()
    if key in ALIASES:
        return ALIASES[key]
    return key.replace(" ", "-")


def committed():
    """peer -> (P, W, F, S) from its committed report."""
    out = {}
    for d in sorted((REPO / "protocol-generator").iterdir()):
        f = d / "status" / "CONFORMANCE-REPORT.json"
        if not f.is_file():
            continue
        try:
            s = json.loads(f.read_text(encoding="utf-8"))["summary"]
        except (OSError, ValueError, KeyError):
            continue
        out[d.name] = (s["passed"], s["warned"], s["failed"], s["skipped"])
    return out


def live_lines(text):
    """(lineno, line) for lines that are not part of a dated `>` note block."""
    for n, line in enumerate(text.splitlines(), 1):
        if line.lstrip().startswith(">"):
            continue
        yield n, line


def tracked_md():
    out = subprocess.run(
        ["git", "ls-files", "-z", "*.md"], cwd=REPO, capture_output=True, text=True, check=True
    ).stdout
    for rel in out.split("\0"):
        if rel and not rel.startswith("docs/adr/ecosystem/"):
            yield rel


def check_rows(reports, matrix_text):
    """Checks 1 + 3. Returns (errors, n_rows)."""
    errors = []
    n = 0
    for lineno, line in live_lines(matrix_text):
        if not line.startswith("| **"):
            continue
        pw = PWFS.search(line)
        if not pw:
            continue
        n += 1
        m = ROW.match(line)
        if not m:
            # Fail closed and SAY SO. A row carrying a published number that this gate
            # cannot parse must never be silently skipped — that is the failure mode where
            # a gate "passes" having examined nothing.
            errors.append(
                f"{MATRIX}:{lineno}  row carries a P/W/F/S but its name cell did not parse: "
                f"{line[:80]!r}"
            )
            continue
        display = m.group(1)
        peer = peer_dir(display)
        if peer not in reports:
            errors.append(
                f"{MATRIX}:{lineno}  row '{display}' -> no peer directory "
                f"'protocol-generator/{peer}/' (add an alias, do not skip the row)"
            )
            continue
        quoted = tuple(int(x) for x in pw.groups())
        actual = reports[peer]
        if quoted != actual:
            errors.append(
                f"{MATRIX}:{lineno}  {display}: published "
                f"{quoted[0]}P/{quoted[1]}W/{quoted[2]}F/{quoted[3]}S but "
                f"{peer}/status/CONFORMANCE-REPORT.json says "
                f"{actual[0]}P/{actual[1]}W/{actual[2]}F/{actual[3]}S"
            )
        hl = HEADLINE.search(line)
        if hl:
            total, fails = int(hl.group(1)), int(hl.group(2))
            got_total = sum(actual)
            if total != got_total or fails != actual[2]:
                errors.append(
                    f"{MATRIX}:{lineno}  {display}: headline '{total} · {fails}F' "
                    f"disagrees with the report ({got_total} · {actual[2]}F)"
                )
    return errors, n


def check_banners(reports):
    """Check 2 — each peer's committed prose banner against its own JSON."""
    errors = []
    n = 0
    for peer, actual in reports.items():
        md = REPO / "protocol-generator" / peer / "status" / "CONFORMANCE-REPORT.md"
        if not md.is_file():
            continue
        head = "\n".join(md.read_text(encoding="utf-8").splitlines()[:15])
        m = BANNER.search(head)
        if not m:
            errors.append(
                f"protocol-generator/{peer}/status/CONFORMANCE-REPORT.md: no parseable banner "
                "in the first 15 lines (regenerate with tools/status-banner.py)"
            )
            continue
        # A banner must anchor on the CONTENT DIGEST, never on the oracle's commit.
        # [ADR-0012] Am. 1: published commits are authored fresh at the release boundary,
        # so a `dev` SHA resolves for no outside reader — and these per-peer files publish
        # (`protocol-generator/**` is outside every doc-root prefix). `status-banner.py` has
        # emitted the digest since 2026-08-28, but the 13 banners the 2026-08-22 HAND pass
        # wrote were never regenerated and still named `entity-core-go @ c1b0708` — a dead
        # dev SHA on the published surface, eight days after the tool that prevents it
        # landed. This is the standing "apply a new anchor to the history you already have,
        # not only to the next entry" rule; nothing was watching the existing instances.
        if ORACLE_COMMIT.search(head):
            errors.append(
                f"protocol-generator/{peer}/status/CONFORMANCE-REPORT.md: banner cites an "
                "oracle COMMIT; a published number must anchor on the content digest "
                f"([ADR-0012] Am. 1) — regenerate with tools/status-banner.py {peer}"
            )
        n += 1
        total, p, w, f, s = (int(x) for x in m.groups())
        quoted = (p, w, f, s)
        if quoted != actual or total != sum(actual):
            errors.append(
                f"protocol-generator/{peer}/status/CONFORMANCE-REPORT.md: banner says "
                f"{total} total · {p}P/{w}W/{f}F/{s}S but its own JSON says "
                f"{sum(actual)} total · {actual[0]}P/{actual[1]}W/{actual[2]}F/{actual[3]}S "
                f"(regenerate with tools/status-banner.py {peer})"
            )
    return errors, n


def check_stale(reports):
    """Check 4 — REPORTED only. P/W/F/S in live prose matching no committed report."""
    known = set(reports.values())
    hits = []
    for rel in tracked_md():
        if rel.startswith(("docs/status/", "docs/archive/")):
            continue
        try:
            text = (REPO / rel).read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        for lineno, line in live_lines(text):
            for m in PWFS.finditer(line):
                if tuple(int(x) for x in m.groups()) not in known:
                    hits.append((rel, lineno, m.group(0)))
    return hits


# Check 5 is SCOPED TO THESE FILES, and the scoping is not fussiness — it is the difference
# between a working check and 124 false positives.
#
# The rule ("a bare §X whose base number this file defines as a top-level section") only
# discriminates while the file's own numbering does not collide with the protocol spec's.
# It holds here: `CONFORMANCE-MATRIX.md` defines §1–§4 and cites the spec at §5–§7b, so the
# spec refs fall outside its numbering and are skipped. It does NOT hold across the tree —
# a peer's `PHASE-S5.md` has a `## 7.` section and cites the spec's §7a/§7b, and the check
# flags every one. Measured before scoping: 124 errors on a clean tree, none of them real.
#
# THE FRAGILITY IS REAL AND WORTH KNOWING: add a `## 5.` section to the matrix and its 5
# genuine spec `§5` citations start resolving as self-refs, so the check goes BLIND rather
# than noisy. That is the safe direction, but it means a clean run here is weaker evidence
# than it looks.
SECREF_FILES = ("CONFORMANCE-MATRIX.md", "README.md", "docs/STATUS.md")


# ---- check 6 ----------------------------------------------------------------
# A sentence that tells a reader which pin a number was measured at. Deliberately a SHORT
# list of present-tense forms: widening it to bare "check set" matches the historical prose
# this repo keeps on purpose, and a check that cannot separate its signal from its noise is
# broken rather than weak.
PIN_PHRASE = re.compile(
    r"(the pin\b|Oracle pin|oracle pin:|pinned as\b|pinned set\b|pinned snapshot\b"
    r"|pinned \d{3}-check|\d{3}-check pin\b|fresh measurement at\b"
    r"|required to execute\b|at one pin\b|at \*\*one\*\* pin\b)",
    re.I,
)
# `7aa6f3de…`, `7aa6f3de...`, or the full 64-hex value.
DIGEST_TOK = re.compile(r"\b([0-9a-f]{8})(?:[0-9a-f]{56}\b|…|\.\.\.)")
# `778-check`, `(778 checks)`, `the 778 checks`
CHECKSET_TOTAL = re.compile(r"\b(\d{3})[- ]check(?:s)?\b")


def pin_facts():
    """(current_digest8, current_total, {retired_digest8}) from tools/oracle-pin.env."""
    env = (REPO / "tools" / "oracle-pin.env").read_text(encoding="utf-8")
    cur = re.search(r"^core_executed_check_set_digest\s*=\s*([0-9a-f]{64})", env, re.M)
    if not cur:
        raise SystemExit("coherence-gate: oracle-pin.env has no core_executed_check_set_digest")
    retired = {
        m.group(1)[:8]
        for m in re.finditer(
            r"^retired_core_executed_check_set_digest\w*\s*=\s*([0-9a-f]{64})", env, re.M
        )
    }
    # The current TOTAL is not a field — it is a property of the committed reports, which
    # check-set-gate has already proved are all at the pinned digest. Deriving it from them
    # rather than from a hand-typed number is the same discipline this check enforces.
    totals = set()
    for d in sorted((REPO / "protocol-generator").iterdir()):
        f = d / "status" / "CONFORMANCE-REPORT.json"
        if f.is_file():
            try:
                totals.add(json.loads(f.read_text(encoding="utf-8"))["summary"]["total"])
            except (OSError, ValueError, KeyError):
                pass
    if len(totals) != 1:
        raise SystemExit(f"coherence-gate: committed reports disagree on total: {sorted(totals)}")
    return cur.group(1)[:8], totals.pop(), retired


# CHANGELOG is an append-only record of what each release WAS measured at; spec-data is a
# frozen boundary; the findings / syntheses / evaluations / diagnostics trees are DATED research
# outputs that carry their date in their own header — this repo holds that a dated record which
# gets back-edited stops being evidence of anything. All of them legitimately name retired pins.
PIN_EXEMPT = (
    "docs/status/",
    "docs/archive/",
    "CHANGELOG.md",
    "protocol-generator/shared/spec-data/",
    "protocol-generator/shared/findings/",
    "protocol-generator/shared/syntheses/",
    "protocol-generator/shared/evaluations/",
    "protocol-generator/shared/diagnostics/",
    "research/",
)
# A struck-through or ✅-marked line is a CLOSED-ITEM record, not a live instruction — the same
# discriminator `link-gate` uses. And a digest introduced by the word "retired"/"superseded" is
# being enumerated as retired, which is the one sentence that must be able to name them all.
HIST_LINE = ("~~", "✅")
HIST_WINDOW = re.compile(r"retired|superseded|no longer|formerly|then-current|then current"
                         r"|first closed", re.I)
# A pin named BESIDE A DATE is a record of what was true on that date. This is the escape
# hatch an author needs, and it is deliberately the cheapest one to reach for: to name a
# retired pin in live prose, put its date next to it or call it "then-current".
DATE_NEAR = re.compile(r"20\d\d-\d\d-\d\d")


def live_paragraphs(text):
    """(first_lineno, joined_text) for each run of consecutive non-blank live lines.

    PER-LINE IS THE WRONG UNIT and this repo has paid for it four times: a backtick span,
    a cited path, and now a retirement clause can all WRAP, so the marker sits on one line
    and the value it governs on the next. Joining the paragraph and recovering the line
    number from the match offset is the fix `link-gate` already uses.
    """
    buf, first = [], None
    for n, line in enumerate(text.splitlines(), 1):
        stripped = line.lstrip()
        if stripped.startswith(">") or not line.strip():
            if buf:
                yield first, " ".join(buf)
                buf, first = [], None
            continue
        # A LIST ITEM, TABLE ROW OR HEADING STARTS A NEW UNIT. Joining a whole bullet list
        # into one paragraph puts every bullet in scope the moment any one of them carries a
        # pin phrase — measured on `README.md`, where bullet 1 names the current pin and
        # bullet 9 recounts a 2026-08-28 measurement at a retired one. Continuation lines of
        # a wrapped bullet stay attached, which is the case the joining exists for.
        if buf and (stripped.startswith(("- ", "* ", "| ", "#"))
                    or re.match(r"\d+[.)]\s", stripped)):
            yield first, " ".join(buf)
            buf, first = [], None
        if first is None:
            first = n
        buf.append(line)
    if buf:
        yield first, " ".join(buf)


def check_pin_statements():
    """Check 6. Returns (errors, n_paragraphs_examined)."""
    cur8, cur_total, retired = pin_facts()
    errors, n = [], 0
    for rel in tracked_md():
        if rel.startswith(PIN_EXEMPT):
            continue
        try:
            text = (REPO / rel).read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        for lineno, para in live_paragraphs(text):
            if not PIN_PHRASE.search(para):
                continue
            if any(mark in para for mark in HIST_LINE):
                continue
            n += 1
            # A value inside a QUOTATION of former text is a record of what this file used
            # to say, not a claim about the pin. This repo corrects prose by quoting the
            # wrong version verbatim beside the right one; that habit must not be gated away.
            quoted, pos = [], 0
            for k, seg in enumerate(para.split('"')):
                if k % 2 == 1:
                    quoted.append((pos, pos + len(seg)))
                pos += len(seg) + 1

            def historical(start, _para=para, _quoted=quoted):
                if any(a <= start < b for a, b in _quoted):
                    return True
                if DATE_NEAR.search(_para[max(0, start - 80):start + 80]):
                    return True
                return bool(HIST_WINDOW.search(_para[:start]))

            for m in DIGEST_TOK.finditer(para):
                if m.group(1) in retired and not historical(m.start()):
                    errors.append(
                        f"{rel}:{lineno}  pin statement names the RETIRED executed-check-set "
                        f"digest `{m.group(1)}…` (current is `{cur8}…`)"
                    )
            for m in CHECKSET_TOTAL.finditer(para):
                if int(m.group(1)) != cur_total and not historical(m.start()):
                    errors.append(
                        f"{rel}:{lineno}  pin statement names `{m.group(0)}` "
                        f"(current set is {cur_total} checks)"
                    )
    return errors, n


def check_secrefs():
    """Check 5 — a bare §X whose base section this file defines, but X does not exist."""
    errors = []
    for rel in SECREF_FILES:
        try:
            text = (REPO / rel).read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        defined = {(g[0], g[1] or "") for g in HEADING.findall(text)}
        if not defined:
            continue
        bases = {b for b, _ in defined}
        for lineno, line in live_lines(text):
            for m in SECREF.finditer(line):
                base, letter = m.group(1), m.group(2) or ""
                if base not in bases:
                    continue  # outside this file's numbering — an external/spec ref
                if (base, letter) not in defined:
                    errors.append(
                        f"{rel}:{lineno}  §{base}{letter} has no matching heading "
                        f"(this file defines §{base} and "
                        f"{sorted('§' + b + l for b, l in defined if b == base)})"
                    )
    return errors


def run(quiet=False):
    reports = committed()
    if not reports:
        print("coherence-gate: ERROR — no committed reports found", file=sys.stderr)
        return 1

    matrix_text = (REPO / MATRIX).read_text(encoding="utf-8")
    row_errs, n_rows = check_rows(reports, matrix_text)
    ban_errs, n_ban = check_banners(reports)
    sec_errs = check_secrefs()
    pin_errs, n_pin = check_pin_statements()
    stale = check_stale(reports)

    if n_pin == 0:
        # A phrase list that matches nothing reports the same word as one that matches
        # everything. This is the assertion, not the empty error list.
        pin_errs = pin_errs + [
            "check 6 examined ZERO pin statements — PIN_PHRASE matches nothing, so the "
            "check is vacuous. Fix the pattern, do not delete the check."
        ]

    errors = row_errs + ban_errs + sec_errs + pin_errs
    if errors:
        print(f"coherence-gate: {len(errors)} COHERENCE FAILURE(S):", file=sys.stderr)
        for e in errors:
            print(f"  {e}", file=sys.stderr)
        print(
            "\nA published number must equal the report it is published from. Refresh the\n"
            "report by MEASURING (tools/run-cohort-census.sh --to-status <peer>), never by\n"
            "editing the prose to match a number you did not re-measure.",
            file=sys.stderr,
        )
        return 1

    if not quiet:
        print(
            f"coherence-gate: OK — {n_rows} §1 rows and {n_ban} peer banners agree with their "
            f"committed reports; {n_pin} pin statement(s) name the current pin"
        )
        if stale:
            print(
                f"coherence-gate: {len(stale)} P/W/F/S in live prose match no committed report "
                "(reported, not gated — this repo quotes superseded figures as evidence):"
            )
            for rel, lineno, tok in stale:
                print(f"    {rel}:{lineno}  {tok}")
    return 0


# --------------------------------------------------------------------------
# Regression suite. A gate without one is a script that has never been wrong
# yet, and this repo has shipped two of those. Each case plants a defect in a
# COPY of the tree's real data and asserts the gate fails on it.
# --------------------------------------------------------------------------

def self_test():
    import copy

    reports = committed()
    matrix_text = (REPO / MATRIX).read_text(encoding="utf-8")
    ok = True

    def expect(name, got, want):
        nonlocal ok
        status = "ok  " if got == want else "FAIL"
        if got != want:
            ok = False
        print(f"  [{status}] {name}: {got} error(s), expected {want}")

    # 0. clean tree must be clean
    errs, n = check_rows(reports, matrix_text)
    expect("clean tree, §1 rows", len(errs), 0)
    print(f"         ({n} rows checked)")
    ban_errs, n_ban = check_banners(reports)
    expect("clean tree, banners", len(ban_errs), 0)
    # A count assertion, not a smoke test. The first cut of check 2 matched the wrong
    # pattern and examined ZERO banners while printing success — a vacuous check reads
    # exactly like a passing one. Pin the number of things actually looked at.
    expect("banners actually examined (not 0)", 0 if n_ban == len(reports) else 1, 0)
    print(f"         ({n_ban} banners checked, {len(reports)} peers)")
    expect("clean tree, self-refs", len(check_secrefs()), 0)

    # Plants 1 and 2 are DERIVED from a real §1 row, never hardcoded. They used to name the
    # literals "313P/336W/0F/106S" and "**755 · 0F** — 313P/336W/0F/106S", which stopped
    # existing at the 756-check re-pin: `assert bad != matrix_text` then fired and took the
    # whole self-test down. That loud failure is correct behaviour — a planting pattern that
    # silently matches nothing would make these two checks vacuous, which is the exact defect
    # check 0's count assertion exists to catch — but a regression suite that must be
    # hand-edited on every re-pin is one nobody runs. Derive the pattern from the file.
    _first = next(
        (ln for _, ln in live_lines(matrix_text) if ln.startswith("| **") and PWFS.search(ln)),
        None,
    )
    assert _first is not None, "no §1 row to plant against"
    _pwfs = PWFS.search(_first).group(0)
    _head = HEADLINE.search(_first)
    assert _head is not None, f"§1 row carries no headline to plant against: {_first[:80]!r}"

    # PLANT ON THE ROW, NOT ON THE DOCUMENT. These two used to `matrix_text.replace(x, y, 1)`,
    # which replaces the first occurrence ANYWHERE — and §1's figures are also quoted in the
    # prose above it. On 2026-09-08 a new disclosure paragraph quoted the cohort-standard
    # `335P/336W/0F/107S`, the plant landed there instead of in a row, check_rows saw an
    # unchanged §1 and reported 0 errors, and the self-test failed. The plant was never
    # wrong about the gate; it was wrong about WHERE it was planting. Substitute inside the
    # row line and splice that one line back, so no amount of prose can absorb it.
    def _plant_in_row(old_line, new_line):
        assert new_line != old_line, "planting failed — pattern absent in the row"
        return matrix_text.replace(old_line, new_line, 1)

    # 1. a row whose number disagrees with its report
    bad = _plant_in_row(_first, _first.replace(_pwfs, "595P/54W/0F/106S", 1))
    assert bad != matrix_text, "planting failed — row absent"
    expect("planted: row number drift", len(check_rows(reports, bad)[0]), 1)

    # 2. a row whose HEADLINE disagrees while its P/W/F/S is right
    _bump = _head.group(0).replace(f"{_head.group(2)}F", f"{int(_head.group(2)) + 3}F")
    bad = _plant_in_row(_first, _first.replace(_head.group(0), _bump, 1))
    assert bad != matrix_text
    expect("planted: headline drift", len(check_rows(reports, bad)[0]), 1)

    # 3. a row naming a peer that does not exist — must ERROR, never silently skip
    bad = matrix_text.replace("| **riscv64** |", "| **riscv-64** |", 1)
    assert bad != matrix_text
    expect("planted: unresolvable row name", len(check_rows(reports, bad)[0]), 1)

    # 4. a peer report the matrix has not caught up with. Two errors, not one, and that is
    # right: the row's P/W/F/S and its `755 · 0F` headline are independent claims and both
    # now disagree. A single error here would mean one of the two checks had not fired.
    drifted = copy.deepcopy(reports)
    drifted["go"] = (999, 1, 0, 106)
    expect("planted: report moved under the row", len(check_rows(drifted, matrix_text)[0]), 2)

    # 4b. a banner that disagrees with its own JSON
    drifted = copy.deepcopy(reports)
    some_peer = "go" if "go" in drifted else sorted(drifted)[0]
    p, w, f, s = drifted[some_peer]
    drifted[some_peer] = (p + 1, w - 1, f, s)
    expect(
        "planted: banner vs its own JSON",
        len([e for e in check_banners(drifted)[0] if some_peer in e]),
        1,
    )

    # 4c. a banner anchored on the oracle's commit instead of the content digest. Planted
    # in the real file, because the check reads from disk. All 13 that carried this form
    # were regenerated 2026-08-30; this is the guard that keeps them that way.
    bmd = REPO / "protocol-generator" / some_peer / "status" / "CONFORMANCE-REPORT.md"
    borig = bmd.read_text(encoding="utf-8")
    try:
        bmd.write_text(
            borig.replace(
                "spec snapshot", "oracle `entity-core-go @ c1b0708`, spec snapshot", 1
            ),
            encoding="utf-8",
        )
        expect(
            "planted: banner anchored on a commit",
            len([e for e in check_banners(reports)[0] if "oracle COMMIT" in e]),
            1,
        )
    finally:
        bmd.write_text(borig, encoding="utf-8")

    # 5. dated `>` note blocks must NOT be gated — they are a build log
    bad = matrix_text + "\n> historical: 595P/54W/0F/106S at the retired pin\n"
    expect("dated `>` block is exempt", len(check_rows(reports, bad)[0]), 0)

    # 6. a dangling self-reference inside a family the file owns
    bad = matrix_text.replace("see §1a.", "see §1z.", 1)
    if bad == matrix_text:
        bad = matrix_text + "\n\nA dangling reference to §1z lives here.\n"
    tmp = REPO / MATRIX
    orig = tmp.read_text(encoding="utf-8")
    try:
        tmp.write_text(bad, encoding="utf-8")
        expect("planted: dangling §1z", len([e for e in check_secrefs() if "§1z" in e]), 1)
    finally:
        tmp.write_text(orig, encoding="utf-8")

    # 7. an external/spec ref outside the file's numbering must NOT be flagged
    bad = matrix_text + "\n\nThe spec's §9z says something.\n"
    try:
        tmp.write_text(bad, encoding="utf-8")
        expect("external §9z not flagged", len([e for e in check_secrefs() if "§9z" in e]), 0)
    finally:
        tmp.write_text(orig, encoding="utf-8")

    # 8–11. check 6 — a retired pin presented as current. Both plants are DERIVED from
    # oracle-pin.env, never hardcoded, for the reason plants 1–2 record: a suite that needs a
    # hand edit on every re-pin is one nobody runs.
    cur8, cur_total, retired = pin_facts()
    _ret8 = sorted(retired)[0]
    base_errs, base_n = check_pin_statements()
    expect("clean tree, pin statements", len(base_errs), 0)
    expect("pin statements actually examined (not 0)", 0 if base_n > 0 else 1, 0)
    print(f"         ({base_n} pin statements checked)")

    try:
        tmp.write_text(
            matrix_text + f"\n\nEvery row here is at the pinned {cur_total - 3}-check set "
            f"`{_ret8}…`.\n",
            encoding="utf-8",
        )
        errs, _ = check_pin_statements()
        # Two independent claims on one line — the digest and the total — so two errors.
        expect("planted: retired pin presented as current", len(errs), 2)
    finally:
        tmp.write_text(orig, encoding="utf-8")

    # 9. the same values ENUMERATED as retired must NOT fire — this is the sentence that has
    # to be able to name every retired pin, and gating it would make the record unwritable.
    try:
        tmp.write_text(
            matrix_text + f"\n\nThe retired pins are the {cur_total - 3}-check set "
            f"`{_ret8}…` and its predecessors; the pin is `{cur8}…`.\n",
            encoding="utf-8",
        )
        errs, _ = check_pin_statements()
        expect("enumerated-as-retired not flagged", len(errs), 0)
    finally:
        tmp.write_text(orig, encoding="utf-8")

    # 10. a dated `>` block naming a retired pin must NOT fire — same deference as check 1.
    try:
        tmp.write_text(
            matrix_text + f"\n\n> Measured at the pinned {cur_total - 3}-check set "
            f"`{_ret8}…`.\n",
            encoding="utf-8",
        )
        errs, _ = check_pin_statements()
        expect("dated `>` block exempt from check 6", len(errs), 0)
    finally:
        tmp.write_text(orig, encoding="utf-8")

    print("\nself-test: " + ("PASS" if ok else "FAIL"))
    return 0 if ok else 1


if __name__ == "__main__":
    if "--self-test" in sys.argv:
        sys.exit(self_test())
    sys.exit(run(quiet="--quiet" in sys.argv))
