#!/usr/bin/env python3
# gen-typestore.py — emit src/typestore.s from the harvested type-entity blobs.
#
# The blobs under reference/typestore/*.bin are the byte-exact `result` entities the
# reference entity-peer serves for `system/tree` get on each `system/type/<name>` path
# (and the one `system/type/` listing). They were captured live through tools/teeproxy.c
# against output/s4-oracles/entity-peer at oracle pin cc1970f — see status/PHASE-S3.md
# and SPEC-AMBIGUITY-LOG A-ASM-006. In an assembly peer there is no data model to reflect
# a type registry over, so these bootstrap entities are harvested byte-exact rather than
# rendered (the keystone "render natively" lesson does not transfer to asm).
#
# Regenerate:  python3 tools/gen-typestore.py > src/typestore.s
#
# The generated store is READ-ONLY (.rodata), so it is shared across the fork-per-connection
# workers for free — no epoll/shared-store refit is needed to serve it.

import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REFDIR = os.path.join(HERE, '..', 'reference', 'typestore')

def load():
    entries = []
    with open(os.path.join(REFDIR, 'manifest.tsv')) as f:
        for line in f:
            path, fn, ln = line.rstrip('\n').split('\t')
            blob = open(os.path.join(REFDIR, fn), 'rb').read()
            assert len(blob) == int(ln), (fn, len(blob), ln)
            entries.append((path, blob))
    return entries

def esc(path):
    # asciz-safe: paths are printable ASCII with no quotes/backslashes
    assert '"' not in path and '\\' not in path and '\n' not in path
    return path

def emit(entries, out):
    w = out.write
    w('# GENERATED by tools/gen-typestore.py — DO NOT HAND-EDIT.\n')
    w('# Byte-exact type-registry bootstrap entities harvested from the reference peer\n')
    w('# (oracle cc1970f) via tools/teeproxy.c. See tools/gen-typestore.py header + A-ASM-006.\n')
    w('# %d entities (%d payload bytes).\n\n' % (len(entries), sum(len(b) for _, b in entries)))
    w('\t.section .rodata\n')
    w('\t.globl type_table\n\t.globl type_table_count\n\n')

    # path strings
    for i, (path, _) in enumerate(entries):
        w('.Ltp%d: .asciz "%s"\n' % (i, esc(path)))
    w('\n')

    # blobs
    w('\t.balign 1\n')
    for i, (_, blob) in enumerate(entries):
        w('.Ltb%d:\n' % i)
        for off in range(0, len(blob), 16):
            chunk = blob[off:off+16]
            w('\t.byte ' + ','.join('0x%02x' % c for c in chunk) + '\n')
    w('\n')

    # table: quad path_ptr, quad path_len(no NUL), quad blob_ptr, quad blob_len
    w('\t.balign 8\n')
    w('type_table:\n')
    for i, (path, blob) in enumerate(entries):
        w('\t.quad .Ltp%d, %d, .Ltb%d, %d\n' % (i, len(path.encode()), i, len(blob)))
    w('type_table_count: .quad %d\n' % len(entries))
    w('\n\t.section .note.GNU-stack,"",@progbits\n')

if __name__ == '__main__':
    emit(load(), sys.stdout)
